/* MouldMaster Book runtime — evidence-governed publication authorization. */
(function(){
  'use strict';
  const VERSION='2026.09.15.5';
  if(window.MMBook?.version===VERSION)return;
  const AUTH_PATH='./data/book-publication-authorization-v1.json';
  const SME_PATH='./data/book-sme-review-v1.json';
  const QUAL_PATH='./data/book-qualification-resolution-all-v1.json';
  const HIGH_RISK_PATH='./data/book-claim-resolution-high-risk-v1.json';
  const BATCH_PATHS=['./data/book-authored-foundations-v1.json','./data/book-evidence-registry-v1.json','./data/book-chapters-materials-machine-v1.json','./data/book-authored-remaining-v1.json'];
  let manifest=null,publicationAuthorization=null,bookSmeReview=null,qualificationReview=null,highRiskReview=null,ui=null,previousView=null,open=false;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stateLabel=state=>({planned:'Planned','source-review':'Source review','technical-review':'Technical review',verified:'Evidence verified',hold:'Hold'}[state]||state);
  async function json(path){const r=await fetch(path,{cache:'no-store'});if(!r.ok)throw new Error(`${path} unavailable (${r.status})`);return r.json();}
  function applyPublicationAuthorization(data,declared,auth){
    if(auth?.schema!==1||auth?.bookId!==data.bookId)throw new Error('Book publication authorization identity check failed');
    if(auth.status!=='authorized')return;
    if(auth?.governanceSnapshot?.manifestVersion!==data.version)throw new Error('Book publication authorization manifest version mismatch');
    const snapshot=auth.governanceSnapshot||{};
    if(snapshot.chapters!==46||snapshot.claims!==137||snapshot.supported!==116||snapshot.qualified!==21||snapshot.hold!==0||snapshot.conflicting!==0||snapshot.scopeQualifiedClaimsBlockingPublication!==0)throw new Error('Book publication authorization governance snapshot mismatch');
    const ids=Array.isArray(auth.authorizedChapterIds)?auth.authorizedChapterIds:[];
    if(ids.length!==declared.size||new Set(ids).size!==ids.length)throw new Error('Book publication authorization chapter coverage mismatch');
    for(const id of ids){const chapter=declared.get(id);if(!chapter)throw new Error(`Book publication authorization contains unknown chapter: ${id}`);chapter.state='verified';}
    publicationAuthorization=auth;
  }
  function validateSmeReview(data,declared){
    if(data?.schemaVersion!==1||data?.bookId!=='mouldmaster-book'||!Array.isArray(data.chapterIds)||!Array.isArray(data.reviews))throw new Error('Book SME review contract identity check failed');
    if(data.chapterIds.length!==declared.size||new Set(data.chapterIds).size!==data.chapterIds.length)throw new Error('Book SME review chapter coverage mismatch');
    for(const id of data.chapterIds)if(!declared.has(id))throw new Error(`Book SME review contains unknown chapter: ${id}`);
    const approved=new Set();for(const review of data.reviews){if(!review?.chapterId||!declared.has(review.chapterId))throw new Error(`Book SME review record has unknown chapter: ${review?.chapterId||'missing'}`);if(review.conclusion==='approved')approved.add(review.chapterId);}
    if(data.status==='validated'&&approved.size!==declared.size)throw new Error('Book SME review cannot be validated without approval coverage for every chapter');
    return data;
  }
  function validateQualificationReview(data){
    if(data?.schema!==1||data?.bookId!=='mouldmaster-book'||!Array.isArray(data.resolutions)||!Array.isArray(data.remainingQualifiedClaims))throw new Error('Book qualification-resolution identity check failed');
    const c=data.effectiveCountsAfterQualificationReview||{};
    if(c.chapters!==46||c.claims!==137||c.supported!==116||c.qualified!==21||c.hold!==0||c.conflicting!==0)throw new Error('Book qualification-resolution counts mismatch');
    return data;
  }
  function smeStatusText(){
    if(!bookSmeReview)return 'Independent human SME review: status unavailable — do not infer approval.';
    const total=bookSmeReview.chapterIds.length,approved=new Set(bookSmeReview.reviews.filter(r=>r?.conclusion==='approved').map(r=>r.chapterId)).size;
    return `Independent human SME review: ${bookSmeReview.status==='validated'&&approved===total?'validated':'pending'} — ${approved}/${total} chapters approved.`;
  }
  async function loadManifest(){
    const data=await json('./data/book-manifest-v1.json');
    if(data?.schema!==1||data?.bookId!=='mouldmaster-book'||!Array.isArray(data.parts)||!Array.isArray(data.sourceSeeds))throw new Error('Book manifest identity check failed');
    const declared=new Map((data.parts||[]).flatMap(p=>p.chapters||[]).map(ch=>[ch.id,ch]));
    if(declared.size!==(data.parts||[]).reduce((n,p)=>n+(p.chapters||[]).length,0))throw new Error('Duplicate chapter id in Book manifest');
    const sourceMap=new Map((data.sourceSeeds||[]).map(source=>[source.id,source]));if(sourceMap.size!==data.sourceSeeds.length)throw new Error('Duplicate source id in Book manifest');
    const authoredIds=new Set(),batches=await Promise.all(BATCH_PATHS.map(path=>json(path)));
    for(const batch of batches){
      if(batch?.schema!==1||batch?.bookId!==data.bookId||!Array.isArray(batch.chapters))throw new Error('Book authored-batch identity check failed');
      for(const source of batch.sourceSeeds||[]){if(!source?.id||!source?.title||!source?.url||!source?.scope)throw new Error('Incomplete Book source record');if(sourceMap.has(source.id))throw new Error(`Duplicate authored source id: ${source.id}`);sourceMap.set(source.id,source);data.sourceSeeds.push(source);}
      for(const authored of batch.chapters){
        if(!authored?.id||authoredIds.has(authored.id))throw new Error(`Duplicate authored chapter id: ${authored?.id||'missing'}`);authoredIds.add(authored.id);
        const chapter=declared.get(authored.id);if(!chapter)throw new Error(`Authored chapter is not declared in manifest: ${authored.id}`);
        const effectiveState=authored.state||(batch.status==='technical-review'?'technical-review':chapter.state);if(effectiveState==='verified')throw new Error(`Authored draft cannot self-promote to verified: ${authored.id}`);
        if(!authored.applicability||!Array.isArray(authored.sections)||!authored.sections.length)throw new Error(`Incomplete authored chapter: ${authored.id}`);
        for(const sourceId of authored.sourceIds||[])if(!sourceMap.has(sourceId))throw new Error(`Unknown source ${sourceId} in ${authored.id}`);
        Object.assign(chapter,authored,{state:effectiveState});
      }
    }
    if(authoredIds.size!==declared.size)throw new Error('Book authored chapter coverage is incomplete');
    applyPublicationAuthorization(data,declared,await json(AUTH_PATH));
    qualificationReview=validateQualificationReview(await json(QUAL_PATH));
    try{highRiskReview=await json(HIGH_RISK_PATH);if(highRiskReview?.schema!==1||highRiskReview?.bookId!==data.bookId)throw new Error('Book high-risk evidence identity mismatch')}catch(error){highRiskReview=null;console.warn('[MouldMaster Book high-risk evidence]',error)}
    try{bookSmeReview=validateSmeReview(await json(SME_PATH),declared)}catch(error){bookSmeReview=null;console.warn('[MouldMaster Book SME status]',error)}
    return data;
  }
  const allChapters=()=> (manifest?.parts||[]).flatMap(part=>part.chapters||[]),verifiedChapters=()=>allChapters().filter(ch=>ch.state==='verified');
  function evidenceMap(){const map=new Map((manifest?.sourceSeeds||[]).map(x=>[x.id,x]));for(const ledger of [highRiskReview,qualificationReview])for(const x of ledger?.newEvidence||[])if(x?.id&&!map.has(x.id))map.set(x.id,x);return map;}
  function evidenceItem(id){const s=evidenceMap().get(id);if(!s)return `<code>${esc(id)}</code>`;const label=esc(s.title||s.id),meta=esc([s.issuer,s.scope].filter(Boolean).join(' — '));return s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener"><b>${label}</b></a>${meta?`<br><small>${meta}</small>`:''}`:`<b>${label}</b>${meta?`<br><small>${meta}</small>`:''}`;}
  function sourceHtml(chapter){const sources=(chapter.sourceIds||[]).map(id=>(manifest.sourceSeeds||[]).find(s=>s.id===id)).filter(Boolean);return sources.length?`<h4>Chapter evidence anchors</h4><ul>${sources.map(s=>`<li>${s.url?`<a href="${esc(s.url)}" target="_blank" rel="noopener"><b>${esc(s.title)}</b></a>`:`<b>${esc(s.title)}</b>`}<br><small>${esc(s.id)} — ${esc(s.scope)}</small></li>`).join('')}</ul>`:'<p>No chapter source anchor has been attached.</p>';}
  function claimTraceHtml(chapter){
    if(!qualificationReview)return '<p><small>Publication claim trace unavailable.</small></p>';
    const prefix=`${chapter.id}-`,resolved=(qualificationReview.resolutions||[]).filter(x=>String(x.claimId||'').startsWith(prefix)),qualified=(qualificationReview.remainingQualifiedClaims||[]).filter(x=>String(x.claimId||'').startsWith(prefix));
    if(!resolved.length&&!qualified.length)return '<p><small>No later qualification decision changed this chapter; use the attached chapter anchors and governed publication authorization.</small></p>';
    const rows=resolved.map(x=>`<li><b>${esc(x.claimId)} — ${esc(x.newConclusion||'reviewed')}</b><p>${esc(x.reason||'')}</p>${(x.evidence||[]).length?`<ul>${x.evidence.map(id=>`<li>${evidenceItem(id)}</li>`).join('')}</ul>`:''}</li>`).join('');
    const qs=qualified.map(x=>`<li><b>${esc(x.claimId)} — scope-qualified</b><p>${esc(x.reason||'')}</p><small>${esc(x.qualificationType||'scope boundary')} · publication blocking: ${x.blockingPublication?'yes':'no'}</small></li>`).join('');
    return `<details class="mm-book-claim-trace"><summary><b>Publication claim trace</b> — why this wording was authorized</summary><p>This trace shows final evidence upgrades and deliberate scope qualifications. It supplements, rather than replaces, the chapter's source anchors.</p><ul>${rows}${qs}</ul></details>`;
  }
  function verifiedChapterHtml(chapter){const sections=Array.isArray(chapter.sections)?chapter.sections:[];return `<article class="mm-book-verified-chapter" data-mm-book-verified-chapter="${esc(chapter.id)}"><span class="eyebrow">Evidence verified</span><h2>${esc(chapter.title)}</h2><p><b>Applicability:</b> ${esc(chapter.applicability||'See attached evidence and controlling documentation.')}</p>${sections.map(s=>`<section><h3>${esc(s.title||'')}</h3><p>${esc(s.text||'')}</p></section>`).join('')}${sourceHtml(chapter)}${claimTraceHtml(chapter)}</article>`;}
  function renderOverview(){if(!ui||!manifest)return;const verified=verifiedChapters(),review=allChapters().filter(ch=>ch.state==='technical-review');ui.summary.textContent=`${manifest.parts.length} parts · ${allChapters().length} governed chapters · ${review.length} in technical review · ${verified.length} evidence-verified for publication`;if(ui.smeStatus)ui.smeStatus.textContent=smeStatusText();ui.parts.innerHTML=(manifest.parts||[]).map((part,partIndex)=>`<section class="card"><span class="eyebrow">Part ${partIndex+1}</span><h3>${esc(part.title.replace(/^Part\s+\d+\s+[—-]\s*/,''))}</h3><div>${(part.chapters||[]).map((chapter,chapterIndex)=>`<button type="button" class="ghost mm-book-chapter-button" data-mm-book-chapter="${esc(chapter.id)}"><b>${chapterIndex+1}. ${esc(chapter.title)}</b><br><small>${esc(chapter.level)} · ${esc(stateLabel(chapter.state))}</small></button>`).join('')}</div></section>`).join('');ui.parts.querySelectorAll('[data-mm-book-chapter]').forEach(b=>b.addEventListener('click',()=>showChapter(b.dataset.mmBookChapter)));ui.listen.disabled=!verified.length;ui.listen.textContent=verified.length?'Listen to evidence-verified Book':'Listening unlocks after evidence verification';}
  function restoreBookChrome(){if(!ui)return;ui.hero.hidden=false;ui.accuracy.hidden=false;}function stopBookSpeech(){try{window.MMReadAloud?.stop?.();}catch(_){}}function showContents(){if(!ui)return;stopBookSpeech();restoreBookChrome();ui.reader.hidden=true;ui.contents.hidden=false;}function bindBack(){ui?.reader?.querySelector('[data-mm-book-back]')?.addEventListener('click',showContents);}
  function showChapter(id){const chapter=allChapters().find(ch=>ch.id===id);if(!chapter||!ui)return;const sections=Array.isArray(chapter.sections)?chapter.sections:[];restoreBookChrome();const back='<button type="button" class="ghost" data-mm-book-back>← Book contents</button>';if(chapter.state==='verified')ui.reader.innerHTML=`${back}${verifiedChapterHtml(chapter)}`;else if(chapter.state==='technical-review'&&sections.length)ui.reader.innerHTML=`${back}<span class="eyebrow">Technical review draft — not evidence verified</span><h2>${esc(chapter.title)}</h2><p><b>Applicability:</b> ${esc(chapter.applicability||'Under review.')}</p><div class="callout"><b>Review boundary:</b> ${esc(chapter.reviewBoundary||'This draft is visible for technical review. Do not treat it as a machine setting, safety procedure or evidence-verified production instruction.')}</div>${sections.map(s=>`<section><h3>${esc(s.title||'')}</h3><p>${esc(s.text||'')}</p></section>`).join('')}${sourceHtml(chapter)}`;else ui.reader.innerHTML=`${back}<span class="eyebrow">${esc(stateLabel(chapter.state))}</span><h2>${esc(chapter.title)}</h2><p><b>This chapter is not being published as technical teaching content yet.</b></p><p>MouldMaster is reviewing the claims, applicability and sources first.</p>${sourceHtml(chapter)}`;ui.contents.hidden=true;ui.reader.hidden=false;bindBack();}
  function startVerifiedListening(){if(!ui)return;const verified=verifiedChapters();if(!verified.length)return;const reader=window.MMReadAloud,details=document.querySelector('.mm-read-aloud details'),play=document.querySelector('.mm-read-aloud [data-mm-read="play"]');if(!reader?.supported||!details||!play){ui.summary.textContent='Evidence-verified Book text is available to read, but device speech synthesis is unavailable.';return;}reader.stop?.();const back='<button type="button" class="ghost" data-mm-book-back>← Book contents</button>';ui.reader.innerHTML=`${back}${verified.map(verifiedChapterHtml).join('')}`;ui.contents.hidden=true;ui.hero.hidden=true;ui.accuracy.hidden=true;ui.reader.hidden=false;bindBack();requestAnimationFrame(()=>{reader.refresh?.();details.open=true;play.click();});}
  function openBook(){if(!ui)return;previousView=[...document.querySelectorAll('.view')].find(v=>!v.classList.contains('hidden')&&v!==ui.view)||previousView;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));ui.view.classList.remove('hidden');restoreBookChrome();open=true;document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));ui.nav.classList.add('active');const title=document.getElementById('pageTitle'),subtitle=document.getElementById('pageSubtitle');if(title)title.textContent='Book';if(subtitle)subtitle.textContent='Evidence-governed injection moulding reference — evidence-verified chapters retain explicit scope and source boundaries.';window.scrollTo({top:0,behavior:'smooth'});}function leaveBook(){if(!open)return;stopBookSpeech();open=false;ui?.view?.classList.add('hidden');ui?.nav?.classList.remove('active');}
  function createUI(){const nav=document.getElementById('nav'),main=document.querySelector('#mainContent,.main,main');if(!nav||!main||document.getElementById('mmBookView'))return;const button=document.createElement('button');button.type='button';button.dataset.mmBookTab='1';button.innerHTML='📖 <span>Book</span>';const listening=nav.querySelector('[data-mm-listening-tab]'),path=nav.querySelector('[data-view="path"]');(listening||path)?.insertAdjacentElement('afterend',button);if(!listening&&!path)nav.prepend(button);const view=document.createElement('section');view.id='mmBookView';view.className='view hidden';view.innerHTML=`<section class="card" data-mm-book-hero><span class="eyebrow">MouldMaster Book</span><h2>Injection moulding from foundations to advanced troubleshooting</h2><p>The Book is source-first and evidence-governed. Evidence-verified chapters retain their applicability and exclusions; machine, material, mould, hot-runner and workplace-specific requirements remain controlling.</p><p data-mm-book-summary>Loading governed Book manifest…</p><p data-mm-book-sme-status class="muted">Loading independent human SME review status…</p><div><button type="button" class="primary" data-mm-book-mode="read">Read Book</button> <button type="button" class="ghost" data-mm-book-mode="listen" disabled>Listening unlocks after evidence verification</button></div></section><section data-mm-book-contents><div data-mm-book-parts></div></section><section class="card" data-mm-book-reader hidden></section><section class="card" data-mm-book-accuracy><h3>Accuracy and assurance boundary</h3><p><b>Evidence verified</b> means the generic Book wording passed MouldMaster's evidence and publication gates. It does not replace current grade, machine, mould, hot-runner, product or site-specific documentation.</p><p><b>Independent validation:</b> evidence verification does not imply independent human SME approval, physical-device validation, curriculum SME approval or learner-outcome validation. Those remain separate external gates.</p></section>`;main.appendChild(view);ui={view,nav:button,hero:view.querySelector('[data-mm-book-hero]'),accuracy:view.querySelector('[data-mm-book-accuracy]'),summary:view.querySelector('[data-mm-book-summary]'),smeStatus:view.querySelector('[data-mm-book-sme-status]'),parts:view.querySelector('[data-mm-book-parts]'),contents:view.querySelector('[data-mm-book-contents]'),reader:view.querySelector('[data-mm-book-reader]'),listen:view.querySelector('[data-mm-book-mode="listen"]')};button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openBook();});view.querySelector('[data-mm-book-mode="read"]').addEventListener('click',showContents);ui.listen.addEventListener('click',startVerifiedListening);}
  async function init(){createUI();try{manifest=await loadManifest();renderOverview();}catch(error){if(ui){ui.summary.textContent='Book manifest, governed content or publication authorization could not be verified. Technical content remains unavailable.';if(ui.smeStatus)ui.smeStatus.textContent='Independent human SME review: status unavailable — do not infer approval.';ui.parts.innerHTML='<section class="card"><h3>Book unavailable</h3><p>The governed Book release failed its runtime identity checks, so MouldMaster has failed closed.</p></section>';}console.error('MouldMaster Book:',error);}}
  document.addEventListener('click',event=>{const target=event.target?.closest?.('nav button,[data-view],[data-page]');if(!target||target.dataset.mmBookTab)return;if(open)leaveBook();},true);
  window.MMBook={version:VERSION,open:openBook,getManifest:()=>manifest,getPublicationAuthorization:()=>publicationAuthorization,getSmeReview:()=>bookSmeReview,getQualificationReview:()=>qualificationReview,verifiedChapters,startVerifiedListening};if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init,{once:true});else init();
})();
