const fs=require('fs'),vm=require('vm'),assert=require('assert');
const memory=new Map();
const localStorage={get length(){return memory.size},key(i){return [...memory.keys()][i]??null},getItem:k=>memory.has(k)?memory.get(k):null,setItem:(k,v)=>memory.set(k,String(v)),removeItem:k=>memory.delete(k)};
const sandbox={console,localStorage,confirm:()=>false,alert:()=>{},document:{querySelectorAll:()=>[]},window:null,db:{},user:{},defaultDB:{activeUser:'learner-1',users:{'learner-1':{id:'learner-1'}}},normaliseImportedUser:(u,id)=>({...u,id}),updateGlobalProgress(){},switchView(){},renderProfile(){},resetData(){},activeExam:null,Blob:function(){},URL:{createObjectURL:()=>'',revokeObjectURL(){}},FileReader:function(){this.readAsText=()=>{}},Date,Math,JSON,Object,Number,String,Array,Map,Set};
sandbox.window=sandbox;vm.createContext(sandbox);vm.runInContext(fs.readFileSync('training-qa-fix.js','utf8'),sandbox);
const fn=sandbox.MM_TRAINING_DATA_BRIDGE.canonicalLearnerId;
for(const good of ['learner-1','learner-1723456789012','learner-A','legacy.user:2','A_1','A+shift@cell'])assert.strictEqual(fn(good),good);
for(const bad of ['', ' learner-1','learner 1','learner\"x','learner<x','learner\nx','x/'.repeat(50),'A'.repeat(161)])assert.throws(()=>fn(bad));
const src=fs.readFileSync('training-qa-fix.js','utf8');
assert(src.includes('const entries=Object.entries(x.users);'));
assert(src.includes("if(entries.length>500)throw new Error('Too many learners in backup')"));
assert(!src.includes('Object.entries(x.users).slice(0,500)'));
assert(src.includes('const sid=canonicalLearnerId(id)'));assert(src.includes('canonicalLearnerId(u.id)!==sid'));assert(src.includes('const active=canonicalLearnerId(x.activeUser)'));
assert(src.includes('hasOwnLearner(x.users,x.activeUser)'));assert(src.includes('Reset learner data'));assert(src.includes('Saved process-data evidence was not deleted'));

sandbox.importData=function(){};sandbox.window.importData=sandbox.importData;
vm.runInContext(fs.readFileSync('src/domains/learning/learner-model.js','utf8'),sandbox);
const validate=sandbox.MM_LEARNER_MODEL.validateBackupEnvelope;
const valid={activeUser:'learner-1',users:{'learner-1':{id:'learner-1',name:'Learner'}}};
assert.strictEqual(validate(JSON.stringify(valid)),true);
const tooMany={activeUser:'learner-0',users:{}};for(let i=0;i<501;i++)tooMany.users[`learner-${i}`]={id:`learner-${i}`};
assert.throws(()=>validate(JSON.stringify(tooMany)),/Too many learners/);
assert.throws(()=>validate(JSON.stringify({activeUser:'toString',users:{}})),/Missing active learner/);
assert.throws(()=>validate(JSON.stringify({activeUser:'learner-1',users:{'learner-1':{id:'different'}}})),/mismatch/);
const guardSrc=fs.readFileSync('src/domains/learning/learner-model.js','utf8');
assert(guardSrc.includes('__mmImportIntegrityGuard'));assert(guardSrc.includes('Object.prototype.hasOwnProperty.call(x.users,x.activeUser)'));
console.log('Import identity integrity QA passed: canonical IDs are aligned, oversized registries fail closed before mutation, own-property activation is required, embedded IDs must match, and the final learning-domain runtime guard prevents packed legacy code from reintroducing truncation.');
