from pathlib import Path


def require(condition, message):
    if not condition:
        raise AssertionError(message)


index = Path("index.html").read_text(encoding="utf-8")
shell = Path("pwa-shell.js").read_text(encoding="utf-8")
reference_page = Path("reference-data.html").read_text(encoding="utf-8")
service_worker = Path("service-worker.js").read_text(encoding="utf-8")
sbom = Path("desktop/electron/scripts/generate-sbom.cjs").read_text(encoding="utf-8")
assessment_qa = Path("qa_assessment_quality.py").read_text(encoding="utf-8")

require("viewport-fit=cover" in index, "mobile viewport must preserve safe-area support")
require("HEAD_ASSETS" in index and "BODY_SCRIPTS" in index, "bootstrap assets must be injected individually")
require("for(const [needle,markup] of HEAD_ASSETS)" in index, "head assets must be checked one by one")
require("for(const [src,tag] of BODY_SCRIPTS)" in index, "runtime scripts must be checked one by one")
require('throw new Error("Core training content is incomplete")' in index, "malformed core content must fail closed")
require("new MutationObserver(scheduleSync)" in shell, "shell DOM sync must be coalesced")
require("el.textContent!==value" in shell, "shell DOM sync must avoid no-op text mutations")
require("syncUpdateCard" in shell and "[data-mm-update-card]" in shell, "runtime version card synchronization missing")
require("dockReferenceLauncher" in shell and "getElementById('mm-src-open')" in shell, "reference launcher docking control missing")
require("document.querySelector('.sidebar-foot')" in shell, "reference launcher must prefer the non-overlay sidebar dock")
require("open.style.position='static'" in shell and "open.style.zIndex='auto'" in shell, "reference launcher must not remain a fixed high-z overlay")
require("configureReferenceDrawer" in shell, "non-blocking reference drawer control missing")
require("modal.setAttribute('aria-modal','false')" in shell, "reference drawer must not claim modal ownership of the whole app")
require("pointer-events:none!important" in shell, "reference drawer backdrop must allow app interaction outside the panel")
require(".mmsrc.mm-reference-drawer .mmsrc-panel{width:min(430px" in shell and "pointer-events:auto!important" in shell, "reference panel itself must remain interactive")
require("calc(82px + env(safe-area-inset-bottom))" in shell, "mobile references drawer must clear the fixed bottom navigation and safe area")
require("max-height:48dvh" in shell, "mobile references drawer must leave working app space visible")

require("REFERENCE_DATA_URL='./reference-data.html'" in shell, "mobile Reference Data must have a dedicated route")
require("openStandaloneReferenceData" in shell and "location.assign(REFERENCE_DATA_URL)" in shell, "mobile Reference Data must navigate to its own document")
require("patchMobileMoreForReferenceData" in shell and "window.openMobileMenu=function()" in shell, "Reference Data must remain reachable from the mobile More menu")
require("data-mm-reference-data-menu" in shell and "Reference data" in shell, "mobile More menu Reference Data action missing")
require("dockReferenceDataLauncher" in shell and "getElementById('mmrd-open')" in shell, "Reference Data launcher docking control missing")
require("open.dataset.mmDocked='mobile-more-standalone-page'" in shell, "mobile Reference Data launcher must be removed from the app surface")
require("open.style.display='none'" in shell, "floating Reference Data launcher must be hidden on mobile")
require(".mmrd.mm-reference-data-drawer,.mmrd.mm-reference-data-drawer[data-open=\"1\"]{display:none!important" in shell, "Reference Data overlay must be impossible on mobile")
require("MM_REFERENCE_DATA_LAUNCHER_DOCK='mobile-more-standalone-page'" in shell, "Reference Data standalone route runtime marker missing")
require("MM_REFERENCE_DATA_DRAWER_MODE='standalone-mobile-page-desktop-drawer'" in shell, "Reference Data desktop/mobile mode marker missing")
require("ensureReferenceDataPage" not in shell and "openReferenceDataPage" not in shell, "legacy in-app Reference Data modal reparenting must be removed")
require("dockReferenceLauncher();configureReferenceDrawer();dockReferenceDataLauncher();configureReferenceDataDrawer();addNZLegacyNote()" in shell, "both reference systems must be normalized during shell synchronization")
require("runSync();\nwindow.addEventListener('resize',scheduleSync" in shell, "reference controls must normalize immediately and on viewport changes")

require('<script src="./reference-data.js"></script>' in reference_page, "standalone Reference Data page must use the canonical data pack")
require('<script src="./reference-2026-expansion.js"></script>' in reference_page, "standalone Reference Data page must load the current practical expansion")
require('id="mm-reference-back"' in reference_page and "history.back()" in reference_page, "standalone Reference Data page must provide app return navigation")
require("position:static!important" in reference_page and ".mmrd-close{display:none!important}" in reference_page, "standalone Reference Data page must not behave like a modal")
require("modal.setAttribute('role','main')" in reference_page and "MM_REFERENCE_DATA_PAGE_MODE='standalone-document-full-library'" in reference_page, "standalone Reference Data page semantics/runtime marker missing")
require("CACHE_VERSION='2026.08.24.1'" in service_worker, "PWA cache version must stay aligned with the browser release")
require("CACHE_REVISION='evidence-approval-20260825'" in service_worker and "${CACHE_VERSION}-${CACHE_REVISION}" in service_worker, "PWA cache revision must advance when the offline learning bundle changes")
require("'./reference-data.html'" in service_worker and "'./reference-2026-expansion.js'" in service_worker, "expanded Reference Data assets must be available offline")
require("'./diagnostic-learning-labs.js'" in service_worker, "Diagnostic Learning Labs must be available offline")
require("'./assessment-evidence-sources.js'" in service_worker and "'./assessment-evidence-approval.js'" in service_worker, "evidence approval assets must be available offline")

require("MM_REFERENCE_DRAWER_MODE='non-blocking'" in shell, "reference drawer runtime mode marker missing")
require("desktopRelease" in shell, "desktop runtime version detection missing")
require("location.hostname==='127.0.0.1'" in shell and "Electron" in shell, "desktop display context must be constrained to the Electron loopback runtime")
require("displayContext().mode==='Desktop package'||!('serviceWorker' in navigator)" in shell, "desktop wrapper must not register the PWA service worker")
require("npm_execpath" in sbom and "result.error" in sbom, "desktop SBOM generation must use the npm CLI entry point and report spawn failures")
require("NamedTemporaryFile" in assessment_qa and "['node','-e',node]" not in assessment_qa, "assessment runtime QA must not exceed OS command-line limits")

print("MouldMaster runtime hardening QA passed")