/* MouldMaster Reference Data Pack — 2026.08.24.1 */
(function(){
'use strict';

const DATA={
  version:'2026.08.24.1',
  note:'Reference data are learning aids, not universal production setpoints. Verify the exact resin grade, supplier data, machine and mould documentation, approved site procedures, and applicable safety requirements before making production changes.',
  materials:[
    {name:'Polypropylene (PP)',family:'Semi-crystalline polyolefin',traits:['low density','good chemical resistance','fatigue resistance','significant mould shrinkage'],watch:['thermal balance and cooling strongly affect shrinkage/warpage','grade stiffness and impact performance vary widely','some filled grades are abrasive'],verify:'Exact grade datasheet, filler/reinforcement level, shrinkage guidance and approved processing window.'},
    {name:'High-density polyethylene (HDPE)',family:'Semi-crystalline polyolefin',traits:['tough','chemical resistant','low moisture uptake','high shrinkage compared with many amorphous polymers'],watch:['warpage can reflect uneven cooling and orientation','long flow paths can magnify pressure loss','density and molecular-weight distribution affect behaviour'],verify:'Grade-specific rheology, shrinkage and dimensional expectations.'},
    {name:'ABS',family:'Amorphous styrenic',traits:['good impact balance','good surface appearance','dimensionally more predictable than high-shrink crystalline resins'],watch:['moisture/contamination can affect appearance','overheating or excessive residence can discolour material','surface finish is sensitive to flow and venting'],verify:'Supplier drying guidance where applicable, colour/additive limits and thermal history.'},
    {name:'Polycarbonate (PC)',family:'Amorphous engineering thermoplastic',traits:['high toughness','good dimensional stability','transparent grades available'],watch:['moisture-sensitive grades require controlled handling','high melt viscosity can increase pressure demand','thermal degradation can cause colour/appearance changes'],verify:'Grade-specific drying/moisture target, residence-time limits and mould-temperature guidance.'},
    {name:'PA6 / PA66 (Nylon)',family:'Semi-crystalline polyamide',traits:['strong','wear resistant','reinforced grades common','properties strongly influenced by absorbed moisture'],watch:['moisture before moulding can cause degradation or appearance issues','post-mould moisture conditioning changes dimensions/properties','glass-filled grades increase wear and anisotropy'],verify:'Exact polymer/grade, reinforcement, drying method, moisture specification and conditioning requirements.'},
    {name:'PBT',family:'Semi-crystalline polyester',traits:['good electrical properties','good chemical resistance','dimensionally useful in reinforced grades'],watch:['hydrolysis risk when processed with excessive moisture','glass-filled grades can show orientation-driven warpage','surface quality depends on fill/venting/thermal balance'],verify:'Supplier moisture/drying specification, reinforcement level and dimensional data.'},
    {name:'PET',family:'Semi-crystalline polyester',traits:['good strength','barrier applications common','crystallisation behaviour depends on grade and thermal history'],watch:['moisture control is critical for molecular-weight retention','crystallisation and cooling affect dimensions and appearance','recycled content can change viscosity/colour'],verify:'Intrinsic-viscosity/grade information, drying method, recycled-content rules and application-specific requirements.'},
    {name:'POM / Acetal',family:'Semi-crystalline engineering thermoplastic',traits:['low friction','good dimensional repeatability','good fatigue performance'],watch:['thermal abuse can cause decomposition','incompatible contamination is a serious processing concern','shrinkage and orientation still require balanced cooling'],verify:'Supplier safety/processing guidance, contamination controls and grade-specific shrinkage.'},
    {name:'PMMA / Acrylic',family:'Amorphous acrylic',traits:['high optical clarity','good weatherability','good surface quality'],watch:['surface defects and flow marks are highly visible','moisture can affect appearance in some grades','scratch sensitivity requires handling control'],verify:'Optical-grade handling, drying if specified, surface requirements and contamination controls.'},
    {name:'TPU',family:'Thermoplastic elastomer',traits:['elastic','abrasion resistant','wide hardness range'],watch:['many grades are moisture sensitive','soft grades can feed/recover differently from rigid pellets','release and ejection can dominate cycle stability'],verify:'Hardness, chemistry family, moisture requirement, release guidance and approved residence limits.'},
    {name:'PPS',family:'High-temperature semi-crystalline engineering polymer',traits:['chemical resistant','dimensionally stable in reinforced grades','high-temperature capability'],watch:['filled grades are often abrasive','tooling and machine wear controls matter','venting and thermal management remain important'],verify:'Reinforcement, corrosion/wear requirements, supplier processing envelope and part-performance specification.'},
    {name:'PEEK',family:'High-performance semi-crystalline polymer',traits:['high-temperature capability','chemical resistance','high mechanical performance'],watch:['requires equipment and tooling suitable for high processing temperatures','crystallinity strongly affects properties','material cost makes purge/startup discipline important'],verify:'Grade-specific supplier processing instructions, machine capability, tooling temperature capability and validated quality plan.'},
    {name:'Polystyrene (PS)',family:'Amorphous styrenic',traits:['easy-flowing grades common','good dimensional stability','clear general-purpose grades available'],watch:['brittleness can make ejection/design features critical','overheating can cause degradation and odour','weld lines and stress concentration can reduce strength'],verify:'Exact grade, impact modification, food/contact status where relevant and supplier processing guidance.'},
    {name:'HIPS',family:'Impact-modified polystyrene',traits:['tougher than general-purpose PS','good processability','opaque'],watch:['rubber modification changes stiffness and appearance','regrind level may affect colour and impact performance','surface gloss may vary with thermal history'],verify:'Grade-specific impact, colour, regrind and dimensional requirements.'},
    {name:'ASA',family:'Weather-resistant styrenic',traits:['good weatherability','good surface appearance','impact-resistant grades available'],watch:['surface and colour consistency depend on material condition','some grades require drying','hot-runner residence should remain within supplier guidance'],verify:'Outdoor exposure requirement, colour, grade-specific drying and thermal limits.'},
    {name:'SAN',family:'Amorphous styrenic copolymer',traits:['clarity','chemical resistance better than PS in some environments','rigid'],watch:['brittleness and notch sensitivity can matter','chemical compatibility is application-specific','surface defects remain visible on clear parts'],verify:'Exact grade chemical-resistance data and mechanical requirements.'},
    {name:'TPE / TPR',family:'Thermoplastic elastomer family',traits:['rubber-like response','overmoulding grades common','wide hardness range'],watch:['bonding depends on substrate and exact chemistry','soft pellets can bridge/feed differently','release and texture can affect demoulding'],verify:'Chemistry family, substrate compatibility, hardness, bonding data and supplier handling guidance.'},
    {name:'LCP',family:'Liquid-crystal polymer',traits:['very high flow in thin sections','high-temperature performance','low flash propensity in suitable tooling but highly anisotropic'],watch:['strong molecular orientation affects dimensions/properties','very small gates and thin sections demand precise tooling','filled grades can be abrasive'],verify:'Flow direction, reinforcement, dimensional orientation and exact tooling guidance.'},
    {name:'PC/ABS',family:'Amorphous polymer blend',traits:['balance of PC toughness and ABS processability','good impact performance','common in housings'],watch:['moisture handling remains important','blend ratio/grade changes thermal and mechanical response','surface and colour can reveal degradation'],verify:'Exact supplier blend grade, drying, flame rating and application requirements.'},
    {name:'Recycled-content compounds',family:'Recycled or mass-balanced thermoplastic compounds',traits:['can reduce virgin-material demand','property range depends heavily on feedstock and formulation'],watch:['lot-to-lot viscosity, colour and contamination may vary','regulatory/contact claims require traceability','multiple heat histories can affect properties'],verify:'Supplier certificate, recycled-content definition, incoming QC, lot traceability and validated process window.'}
  ],
  defects:[
    {name:'Short shot',evidence:'Incomplete fill or unfilled extremities.',check:['fill pattern and flow restriction','actual fill time and pressure demand','material condition and thermal actuals','venting at end-of-fill locations'],avoid:'Do not assume injection speed alone is the cause.'},
    {name:'Flash',evidence:'Excess material at parting lines, inserts, vents or shutoffs.',check:['exact flash location','tool seating/parting-line condition','clamp performance and actual cavity pressure demand','local damage, wear or contamination'],avoid:'Do not use clamp force to hide a damaged shutoff without investigation.'},
    {name:'Sink marks',evidence:'Local surface depressions, often over thick sections or ribs.',check:['local section thickness','gate effectiveness and gate-seal evidence','packing response and part mass','local cooling balance'],avoid:'Do not extend hold time blindly after the gate has stopped transmitting useful pressure.'},
    {name:'Warpage',evidence:'Part shape departs from intended geometry after moulding.',check:['mould temperature balance','cooling circuit condition','orientation and fibre direction','packing balance and ejection condition'],avoid:'Treat warpage as a multi-factor dimensional response, not a single-setting defect.'},
    {name:'Burn / dieseling',evidence:'Dark, scorched or degraded area, often near trapped gas/end of fill.',check:['defect location relative to end of fill','vent condition and gas escape path','local fill velocity/compression of trapped air','material degradation evidence'],avoid:'Do not bypass guarding or open a running mould to inspect vents.'},
    {name:'Splay / silver streaks',evidence:'Silver or pale streaking on the surface.',check:['material moisture and handling history','contamination or volatiles','thermal degradation/residence evidence','decompression or air entrainment where relevant'],avoid:'Do not apply one generic drying recipe across resin families.'},
    {name:'Weld / knit line weakness',evidence:'Visible or weak line where flow fronts meet.',check:['flow-front location and geometry','venting at the meeting point','material/thermal condition','local pressure and orientation'],avoid:'Appearance alone does not prove mechanical acceptability.'},
    {name:'Jetting',evidence:'Snake-like or folded flow trace from a gate.',check:['gate direction and local geometry','initial flow-front behaviour','fill profile and local impingement','material viscosity/thermal condition'],avoid:'Do not change several fill variables at once; confirm the flow mechanism.'},
    {name:'Delamination',evidence:'Layer-like separation or flaking surface.',check:['material compatibility/contamination','masterbatch or additive compatibility','moisture/volatile history','excessive shear or degraded material evidence'],avoid:'Do not regrind suspect mixed material back into production until identity is controlled.'},
    {name:'Black specks',evidence:'Dark inclusions or degraded particles.',check:['purge history and dead spots','residence/thermal history','contamination routes','screw/barrel/nozzle/hot-runner condition'],avoid:'Do not simply increase temperature to clear degraded material.'},
    {name:'Voids / internal bubbles',evidence:'Internal cavities not open to the surface.',check:['section thickness and solidification pattern','packing effectiveness before gate seal','material volatiles/moisture evidence','part sectioning or non-destructive evidence'],avoid:'Do not confuse vacuum voids with gas bubbles without examining the mechanism.'},
    {name:'Gloss variation',evidence:'Uneven surface reflectivity across the part or between shots.',check:['mould surface and contamination','local mould temperature','flow-front speed/pressure at the surface','material/additive/colour consistency'],avoid:'Cosmetic variation can be local even when machine settings are global.'},
    {name:'Stringing / drool',evidence:'Material strings or leaks from nozzle/gate between cycles.',check:['nozzle/hot-runner thermal condition','material viscosity and degradation','decompression strategy if applicable','gate/nozzle shutoff condition'],avoid:'Do not compensate indefinitely for a leaking mechanical shutoff with process changes.'},
    {name:'Ejection marks / sticking',evidence:'Scuffing, whitening, pin marks, drag or difficult release.',check:['draft and texture','local cooling/part rigidity','ejector condition and alignment','packing level and release geometry'],avoid:'Robot force is not a substitute for safe, reliable part release.'},
    {name:'Flow marks',evidence:'Visible bands, halos or surface changes associated with flow-front history.',check:['location relative to gate/geometry changes','local mould surface temperature','fill-front speed changes','material thermal state'],avoid:'Do not classify every cosmetic band as the same mechanism.'},
    {name:'Record grooves / tiger stripes',evidence:'Alternating gloss or flow bands, often seen in some filled or elastomeric systems.',check:['material formulation','flow-front stability','wall thickness and gate geometry','fill profile evidence'],avoid:'Confirm the material/flow mechanism before making broad thermal changes.'},
    {name:'Gate blush',evidence:'Local whitening, haze or stress appearance around the gate.',check:['gate geometry and entry direction','local shear/velocity','material stress sensitivity','gate vestige and ejection interaction'],avoid:'Do not assume mould temperature alone controls a gate-local defect.'},
    {name:'Cold slug mark',evidence:'Comet-like or irregular mark linked to cooler material entering the cavity.',check:['nozzle condition','sprue/cold-slug provision','startup/purge sequence','hot-runner or nozzle thermal uniformity'],avoid:'Separate cold-material evidence from moisture or contamination streaks.'},
    {name:'Diesel cracking / vent erosion',evidence:'Tool damage or surface deterioration near repeated trapped-gas combustion zones.',check:['vent depth/condition to approved tool standard','end-of-fill location','gas generation/contamination','local fill-front compression'],avoid:'Do not keep producing through progressive tool damage.'},
    {name:'Dimensional drift',evidence:'Measured dimensions move over time while parts may still look acceptable.',check:['mould thermal balance','material lot/conditioning','packing and part-mass trends','measurement system and conditioning time'],avoid:'Never adjust a process from a single unverified measurement.'}
  ],
  signals:[
    {name:'Fill time',meaning:'Time required for the controlled filling phase.',use:'Trend repeatability and compare with pressure/transfer evidence.',drift:'A change can indicate viscosity, thermal, flow restriction, machine response or profile changes.'},
    {name:'Peak injection pressure',meaning:'Maximum pressure demand observed during filling.',use:'Compare pressure demand at similar fill conditions.',drift:'Higher demand can reflect colder/more viscous material, restriction, venting effects or changed flow rate.'},
    {name:'Transfer position',meaning:'Screw position at velocity-to-pressure transfer.',use:'Track shot delivery and consistency of the filled volume at transfer.',drift:'Movement can indicate delivery variation, check-ring behaviour or changed material compressibility.'},
    {name:'Cushion',meaning:'Material/screw position remaining after packing.',use:'Trend with part mass, transfer and pressure.',drift:'Variation can reveal unstable shot delivery or non-return-valve behaviour.'},
    {name:'Recovery time',meaning:'Time required to plasticise/meter the next shot.',use:'Trend feed, plasticising and cooling overlap.',drift:'Changes can point to feed, material, screw speed, back pressure or thermal condition.'},
    {name:'Screw recovery position',meaning:'Metered shot position before injection.',use:'Confirm shot-size repeatability.',drift:'Unexpected variation should be investigated before compensating elsewhere.'},
    {name:'Melt temperature actual',meaning:'Measured melt temperature using an approved method.',use:'Validate thermal state rather than assuming barrel setpoints equal melt condition.',drift:'Can reflect residence, shear, heater performance or measurement method.'},
    {name:'Mould-surface temperature',meaning:'Temperature at relevant cavity/core surfaces.',use:'Check thermal balance and repeatability.',drift:'Can affect fill, surface, shrinkage, warpage, ejection and cycle stability.'},
    {name:'Cooling-water supply/return',meaning:'Thermal-fluid temperatures entering/leaving a circuit.',use:'Use with flow information to diagnose cooling-system changes.',drift:'Temperature alone does not prove adequate flow or correct circuit connection.'},
    {name:'Part mass',meaning:'Mass of a defined part/shot sample.',use:'Simple response for filling/packing consistency when measurement is controlled.',drift:'Can correlate with transfer, packing, leakage, cavity balance or material variation.'},
    {name:'Cycle phase times',meaning:'Fill, hold, cooling, recovery and mould-motion durations.',use:'Identify which phase changed when total cycle time moves.',drift:'A stable total can still hide compensating phase changes.'},
    {name:'Clamp force actual',meaning:'Measured/estimated force used to keep the mould closed.',use:'Compare with validated mould/process requirements.',drift:'Must not be treated as a substitute for fixing flash-causing tooling damage.'},
    {name:'Cavity pressure',meaning:'Pressure measured inside the mould when cavity sensors are available.',use:'Connect machine events to local filling, transfer, packing and gate-seal behaviour.',drift:'Interpret by sensor location, calibration and the event being measured.'},
    {name:'Hydraulic / plastic pressure relationship',meaning:'Machine-specific relationship between hydraulic pressure and plastic pressure.',use:'Translate controller values only with the machine documentation and intensification ratio where applicable.',drift:'Never assume values transfer directly between different machine designs.'},
    {name:'Dryer dew point / air condition',meaning:'Condition of drying air for systems where it is relevant.',use:'Use alongside temperature, airflow, residence time and material moisture measurement.',drift:'A good displayed dew point alone does not prove dry resin at the hopper outlet.'},
    {name:'Reject pattern by cavity/time',meaning:'Where and when defects occur across cavities and production time.',use:'Separate local tooling causes from machine/material/system causes.',drift:'Patterns are often more diagnostic than the overall reject percentage.'},
    {name:'Injection velocity actual',meaning:'Measured screw/injection velocity during the fill profile.',use:'Confirm the machine follows the intended profile and compare across machines carefully.',drift:'Servo/hydraulic limits, pressure limitation or maintenance condition can prevent the commanded profile.'},
    {name:'Hold pressure actual',meaning:'Actual pressure response during packing/holding.',use:'Compare with cavity pressure, mass and gate-seal evidence.',drift:'Controller setpoint alone does not prove pressure was transmitted into the cavity.'},
    {name:'Screw torque / drive load',meaning:'Load required during screw recovery where the machine exposes it.',use:'Trend plasticising resistance and changes in feed/material behaviour.',drift:'Material condition, screw wear, feed restriction or temperature can change load.'},
    {name:'Mould-open / eject time',meaning:'Time spent in opening, ejection and closing motion.',use:'Separate mechanical handling losses from polymer cooling time.',drift:'Can reveal sticking, robot delays, lubrication issues or motion-profile changes.'},
    {name:'Hot-runner zone actuals',meaning:'Measured zone temperatures and controller output for a hot-runner system.',use:'Compare zones and trend heater/control abnormalities.',drift:'A displayed temperature may remain near setpoint while heater output or material residence indicates a fault.'},
    {name:'Cooling-circuit flow',meaning:'Measured coolant flow where instrumentation exists.',use:'Pair with supply/return temperature and circuit identification.',drift:'Blocked, reversed, air-locked or misconnected circuits can change thermal balance.'}
  ],
  tooling:[
    {name:'Gate',purpose:'Controls entry of melt into the cavity and strongly influences local shear, freeze-off and vestige.',inspect:['damage/wear','location and cross-section','gate balance between cavities','evidence of freeze or drool'],remember:'Gate behaviour is local; global process changes can hide a tooling problem.'},
    {name:'Runner system',purpose:'Carries melt from sprue/nozzle to one or more gates.',inspect:['branch balance','diameter transitions','cold-slug locations','hot-runner temperature consistency where applicable'],remember:'Unequal pressure loss can create cavity imbalance even with a stable machine.'},
    {name:'Vent',purpose:'Provides controlled escape for displaced air and process gases.',inspect:['end-of-fill location','contamination or blockage','damage/erosion','approved depth and land condition'],remember:'Vent dimensions are material/tool specific—use the approved tool standard rather than generic numbers.'},
    {name:'Parting line',purpose:'Interface between mould halves or components.',inspect:['damage','contamination','support/seating','flash pattern'],remember:'Local flash at a damaged parting line should not be solved by escalating clamp force.'},
    {name:'Ejector pins',purpose:'Apply controlled force to release the moulded part.',inspect:['alignment','wear/bending','marking pattern','return condition'],remember:'Ejection problems often combine part rigidity, draft, texture and tooling condition.'},
    {name:'Sleeve / blade ejector',purpose:'Provides ejection in geometries where standard pins are unsuitable.',inspect:['wear','alignment','lubrication policy','witness marks'],remember:'Thin ejector elements are vulnerable to damage and must be maintained to toolmaker specifications.'},
    {name:'Lifter',purpose:'Releases undercuts while contributing to part ejection.',inspect:['timing','wear/galling','angle and travel','part witness marks'],remember:'A sticking lifter can look like a process or robot problem.'},
    {name:'Slider / side action',purpose:'Forms side features and retracts before ejection.',inspect:['locking','timing','wear','lubrication and debris'],remember:'Interlocks and machine sequence must never be bypassed to compensate for a sticking side action.'},
    {name:'Core pin',purpose:'Forms internal holes or narrow features and conducts heat locally.',inspect:['bending','wear','cooling where fitted','flash or mismatch'],remember:'Thin cores can deflect under pressure and may create dimensional or concentricity problems.'},
    {name:'Cooling channel',purpose:'Removes heat from the mould and shapes the thermal field.',inspect:['circuit identification','flow','scale/blockage','supply/return connection'],remember:'Balanced temperature requires both suitable coolant condition and actual flow.'},
    {name:'Baffle / bubbler',purpose:'Directs coolant into narrow or deep tool regions.',inspect:['orientation','seal condition','flow restriction','corrosion/scale'],remember:'Incorrect assembly can reverse or severely reduce intended cooling.'},
    {name:'Sprue bushing',purpose:'Connects the machine nozzle to a cold-runner mould.',inspect:['nozzle seat','surface damage','pull/release condition','cold slug behaviour'],remember:'Poor nozzle-to-sprue contact can leak, drool or create unstable material entry.'},
    {name:'Hot-runner manifold',purpose:'Distributes molten polymer through heated channels.',inspect:['zone balance','leak evidence','heater/thermocouple behaviour','residence and dead spots'],remember:'A temperature reading alone does not prove melt condition everywhere in the manifold.'},
    {name:'Valve gate',purpose:'Mechanically opens/closes a hot-runner gate to control flow timing and vestige.',inspect:['pin timing','stroke','wear','actuation consistency'],remember:'Timing imbalance can create fill or weld-line differences between cavities.'},
    {name:'Mould support / pillars',purpose:'Resists deflection of mould plates under clamping and cavity pressure.',inspect:['damage','contact condition','plate deflection evidence','fastener condition'],remember:'Structural deflection can cause flash or dimensional variation even if nominal clamp force is adequate.'},
    {name:'Texture / surface finish',purpose:'Creates appearance, function or release characteristics.',inspect:['direction relative to draw','damage/polish','contamination','required draft'],remember:'A texture change can alter demoulding force and cosmetic response.'}
  ],
  machine:[
    {name:'Injection screw',role:'Plasticises, meters and injects polymer.',watch:['wear','material compatibility','recovery consistency','screw design relative to resin'],evidence:'Recovery time, shot repeatability, torque/load and melt quality.'},
    {name:'Barrel',role:'Contains the screw and heated polymer.',watch:['wear','heater condition','contamination/dead spots','residence volume'],evidence:'Melt condition, pressure capability, purge behaviour and dimensional wear records.'},
    {name:'Non-return valve / check ring',role:'Limits reverse flow during injection.',watch:['wear','contamination','repeatability','material-sensitive behaviour'],evidence:'Cushion, transfer position, part mass and pressure repeatability.'},
    {name:'Nozzle',role:'Connects injection unit to sprue or hot-runner inlet.',watch:['seat contact','leakage','heater/thermocouple','freeze/drool'],evidence:'Nozzle leakage, cold slugs, pressure loss and thermal readings.'},
    {name:'Hopper / feed throat',role:'Feeds pellets into the plasticising unit.',watch:['bridging','feed-throat cooling','contamination','material segregation'],evidence:'Recovery stability, feed interruptions and material condition.'},
    {name:'Heater zones',role:'Provide controlled barrel/nozzle heat.',watch:['heater output','thermocouple placement/failure','overshoot','zone interaction'],evidence:'Actual temperatures, controller output and measured melt temperature.'},
    {name:'Injection drive',role:'Moves the screw forward under velocity/pressure control.',watch:['pressure limitation','servo/hydraulic performance','maintenance condition','profile tracking'],evidence:'Velocity actuals, pressure actuals and fill-time repeatability.'},
    {name:'Screw-rotation drive',role:'Rotates the screw for plasticising/recovery.',watch:['torque/load','speed actual','oil/servo condition','mechanical wear'],evidence:'Recovery time, torque/load and shot preparation stability.'},
    {name:'Clamp unit',role:'Opens/closes the mould and resists cavity-opening force.',watch:['platen parallelism','tie-bar condition','force calibration','mould protection settings'],evidence:'Flash pattern, clamp-force actuals, mould movement and maintenance records.'},
    {name:'Mould protection / low-pressure close',role:'Detects obstruction before full clamp force.',watch:['approved setup','repeatability','sensor/position calibration','unauthorised bypass'],evidence:'Close profile and alarms; never defeat the safeguard to maintain production.'},
    {name:'Ejector system',role:'Drives mould ejector mechanism.',watch:['stroke','force/pressure','return confirmation','sequence interlocks'],evidence:'Ejection time, marks, sticking and sensor status.'},
    {name:'Core-pull circuit',role:'Actuates hydraulic/pneumatic/electric mould actions.',watch:['sequence','leaks','position confirmation','pressure/force'],evidence:'Cycle alarms, timing and actual position feedback.'},
    {name:'Machine controller',role:'Coordinates profiles, sequences, alarms and data acquisition.',watch:['recipe revision','units','permissions','software/configuration changes'],evidence:'Audit trail, setpoint vs actual trends and alarm history.'},
    {name:'Robot interface',role:'Coordinates machine and external automation safely.',watch:['handshake signals','safe states','sequence timing','guarding'],evidence:'I/O trace, robot alarms and safety-system status.'},
    {name:'Hydraulic system',role:'Provides controlled force/motion on hydraulic machines.',watch:['oil temperature','filter/contamination','leakage','pump/valve response'],evidence:'Pressure/velocity repeatability and maintenance data.'},
    {name:'All-electric servo system',role:'Uses servo drives for major machine axes.',watch:['drive alarms','position calibration','load/torque trends','mechanical transmission'],evidence:'Position/velocity/load traces and drive diagnostics.'}
  ],
  quality:[
    {name:'First-off approval',purpose:'Confirms startup parts meet defined requirements before routine production.',good:['defined sampling','approved measurement method','traceable material/tool/machine state','documented disposition'],risk:'A visual-only first-off can miss dimensional or functional drift.'},
    {name:'Control plan',purpose:'Defines what is controlled, measured, sampled and reacted to during production.',good:['clear characteristic ownership','reaction plan','measurement method','revision control'],risk:'A control plan that is not connected to actual process evidence becomes paperwork rather than control.'},
    {name:'Measurement system analysis',purpose:'Checks whether the measurement process is adequate for the decision.',good:['repeatability/reproducibility considered','fixtures/method controlled','resolution suitable','operators trained'],risk:'Process capability is meaningless if measurement variation dominates.'},
    {name:'Cp / Cpk',purpose:'Summarises short-term potential/performance relative to specification under assumptions.',good:['stable process','adequate measurement','appropriate distribution/context','sufficient representative data'],risk:'A single Cpk value is not proof of validation or long-term control.'},
    {name:'Pp / Ppk',purpose:'Describes overall performance using observed variation over the sampled period.',good:['time period defined','data representative','special causes understood','measurement adequate'],risk:'High performance indices can hide sampling that excluded real operating variation.'},
    {name:'SPC chart',purpose:'Separates common-cause variation from signals of process change.',good:['correct chart type','rational subgrouping','reaction rules','data collected consistently'],risk:'Control limits are not product specification limits.'},
    {name:'DOE',purpose:'Tests factor effects/interactions using a planned experimental structure.',good:['clear response','randomisation/blocking as needed','interaction strategy','measurement suitable'],risk:'One-factor-at-a-time or uncontrolled trial-and-error is not a designed experiment.'},
    {name:'Process window study',purpose:'Establishes evidence about acceptable operation across selected factors.',good:['quality responses defined','machine actuals recorded','factor ranges justified','boundaries confirmed'],risk:'A copied machine recipe is not a validated process window.'},
    {name:'Cavity balance study',purpose:'Compares fill/pack response across cavities.',good:['individual cavity identification','controlled shot progression or sensor data','mass/dimension evidence','repeatability'],risk:'Combined shot mass can hide one heavy and one light cavity.'},
    {name:'Gate-seal study',purpose:'Identifies when additional hold time no longer meaningfully changes the selected response.',good:['controlled hold-time steps','part mass/dimension response','thermal condition stable','appropriate cooling/conditioning'],risk:'Plateau evidence is application-specific; it is not a universal hold-time formula.'},
    {name:'Short-shot study',purpose:'Reveals filling pattern and cavity balance.',good:['safe approved procedure','incremental controlled shots','cavity mapping','photographic/weight evidence'],risk:'Never defeat guards or interlocks to observe filling.'},
    {name:'Process audit trail',purpose:'Records who changed what, when and why.',good:['recipe revision history','authorisation','reason for change','result/verification'],risk:'Unlogged adjustments destroy traceability and make troubleshooting much harder.'},
    {name:'Traceability',purpose:'Connects product to material, machine, mould, process and inspection evidence.',good:['lot/batch identity','time/cavity where required','recipe/revision','inspection record'],risk:'Traceability must match product risk and customer/regulatory requirements.'},
    {name:'Capability vs tolerance review',purpose:'Checks whether observed variation is compatible with engineering tolerance.',good:['datum/measurement method clear','distribution/stability reviewed','cavity/time effects separated','customer criteria used'],risk:'Do not tighten process controls around an unverified drawing or measurement method.'}
  ],
  safety:[
    {name:'Guard/interlock status',check:'All required guards and interlocks function as designed before production or troubleshooting.',why:'Access to clamp, ejector, screw, robot or other hazardous motion can cause severe injury.',never:'Never bypass, tape, defeat or code around a safeguard to maintain output.'},
    {name:'Isolation / lockout',check:'Use the site-approved hazardous-energy isolation procedure before entering or servicing hazardous zones.',why:'Stored hydraulic, pneumatic, electrical, thermal and gravitational energy may remain after stop.',never:'A stop button or open guard is not automatically an energy-isolation procedure.'},
    {name:'Hot surfaces / molten polymer',check:'Treat nozzle, barrel, hot runner, purge material and recently ejected parts as potential burn hazards.',why:'Molten polymer can eject unexpectedly and remains hot after appearance changes.',never:'Do not stand in line with purge/nozzle discharge or handle hot purge without approved controls.'},
    {name:'High-pressure polymer',check:'Follow machine/tool procedures before opening any pressurised melt path.',why:'Trapped melt pressure can release suddenly from nozzle, hot runner or blocked passages.',never:'Do not loosen a nozzle, heater band or hot-runner component to relieve pressure casually.'},
    {name:'Mould movement',check:'Confirm safe state before work between platens or around moving mould actions.',why:'Clamp and core-pull systems can generate crushing forces.',never:'Never rely on software state alone where formal mechanical/energy isolation is required.'},
    {name:'Robot / automation cell',check:'Treat machine, robot, conveyor and auxiliaries as one integrated safety system.',why:'Unexpected restart or independent axis motion can occur during fault recovery.',never:'Do not cross guarding because one device appears stopped.'},
    {name:'Purge and material change',check:'Use the resin supplier and site-approved purge/changeover procedure.',why:'Some polymers are chemically incompatible or can decompose dangerously when mixed/overheated.',never:'Do not improvise high-temperature purging for an unknown or incompatible material combination.'},
    {name:'Compressed air',check:'Use only approved methods for cleaning/cooling and protect against projected particles.',why:'Compressed air can inject debris, spread contamination or create flying particles.',never:'Do not use compressed air on skin or as an informal personal-cleaning method.'},
    {name:'Lifting moulds',check:'Use rated lifting points, lifting equipment and site procedures.',why:'Moulds are heavy, concentrated loads with severe crush potential.',never:'Do not assume eyebolts, straps or fork positions are suitable without rating/inspection.'},
    {name:'Chemical handling',check:'Follow SDS/site requirements for cleaners, release agents, additives and maintenance chemicals.',why:'Flammability, inhalation, skin and compatibility risks vary by product.',never:'Do not mix chemicals or use unlabelled containers.'},
    {name:'Granulator / regrind equipment',check:'Guard and isolate size-reduction equipment before clearing jams or maintenance.',why:'Rotating blades and stored inertia create severe hazards.',never:'Do not reach through feed openings or defeat interlocks.'},
    {name:'Fume / decomposition response',check:'Stop and follow emergency/site ventilation procedures if unusual smoke, odour or decomposition is suspected.',why:'Overheated polymers can release hazardous decomposition products.',never:'Do not lean over a hopper/nozzle to identify fumes by smell.'}
  ],
  troubleshooting:[
    {name:'Only one cavity changes',pattern:'One cavity becomes light, flashed, short or dimensionally different while others remain stable.',first:['inspect the affected branch/gate/vent/cooling/ejection','compare cavity-specific mass/pressure/appearance','check recent local tool work'],avoid:'Global machine changes before ruling out local tooling causes.'},
    {name:'All cavities change together',pattern:'Every cavity shifts at roughly the same time.',first:['check material lot/condition','machine actuals and thermal state','common hot-runner/cooling supply','recent recipe or machine change'],avoid:'Starting with one cavity-specific tool adjustment.'},
    {name:'Drift after water-line work',pattern:'Dimensions, cycle or release changes immediately after hoses/circuits were disturbed.',first:['verify circuit identity and connection','confirm actual flow and supply/return temperatures','compare mould-surface temperature'],avoid:'Changing pack/fill settings before checking the changed thermal system.'},
    {name:'Fill time rises slowly',pattern:'Saved recipe is constant but fill time/pressure demand drifts over time.',first:['compare actual melt/mould thermal conditions','material handling and lot','injection velocity actual','flow restriction/venting'],avoid:'Forcing fill time back with speed before finding why actual response changed.'},
    {name:'Cushion and part mass vary together',pattern:'Shot delivery evidence and product mass move together.',first:['check non-return valve consistency','recovery/feed stability','transfer position','material feed condition'],avoid:'Using more hold pressure to mask unstable shot delivery.'},
    {name:'Recovery becomes erratic',pattern:'Recovery time or screw load becomes unstable while cooling time is unchanged.',first:['material feed/bridging','dryer/hopper condition','screw/back-pressure actuals','temperature and drive load'],avoid:'Changing mould cooling to solve a plasticising problem.'},
    {name:'Burn at end of fill',pattern:'Dark/burned defect repeatedly appears at the last filling region.',first:['confirm fill-front location','inspect approved vent condition','check trapped-gas route','review local fill-front speed'],avoid:'Assuming polymer degradation without examining gas escape.'},
    {name:'Flash after tool maintenance',pattern:'Local flash begins immediately after mould work.',first:['parting-line/shutoff seating','insert/slide assembly','debris or damage','mould support/contact'],avoid:'Increasing clamp force before checking assembly.'},
    {name:'Sticking after texture change',pattern:'Ejection force/marks rise after surface texture or polish modification.',first:['draft vs texture direction','local cooling/part rigidity','ejector balance','surface condition'],avoid:'Increasing robot pull force as the primary solution.'},
    {name:'Splay after humid exposure',pattern:'Streaks appear after material was exposed or handling changed.',first:['verify grade moisture requirement','dryer operation','material exposure/history','approved moisture test'],avoid:'Changing injection settings before checking material condition.'},
    {name:'Black specks after long stop',pattern:'Dark contamination appears after restart or extended residence.',first:['review shutdown/startup/purge procedure','residence and hot spots','nozzle/hot-runner dead spots','contamination sources'],avoid:'Raising temperatures indiscriminately.'},
    {name:'Dimension changes by shift',pattern:'Measurements differ between operators/shifts more than expected.',first:['measurement method/fixture','conditioning time','machine warm-up state','material and environmental differences'],avoid:'Calling it process drift before checking the measurement system.'},
    {name:'Cycle time increases but fill is stable',pattern:'Total cycle rises while filling evidence remains repeatable.',first:['split total cycle into cooling/recovery/mould/robot phases','inspect sticking/ejection','check recovery overlap and auxiliary delays'],avoid:'Optimising injection speed when the lost time is elsewhere.'},
    {name:'Pressure spikes with similar fill time',pattern:'Peak pressure becomes erratic although fill time remains near target.',first:['flow restriction or gate condition','check-ring events','velocity profile actual','sensor/controller event timing'],avoid:'Judging process stability from fill time alone.'},
    {name:'Hot-runner cavity imbalance',pattern:'A group of cavities associated with one manifold branch changes together.',first:['zone actual/output','valve-gate timing if fitted','branch leak/restriction evidence','cavity-specific mass/pressure'],avoid:'Treating grouped cavities as random rejects.'},
    {name:'Weld line moved',pattern:'Weld/knit location shifts from the validated position.',first:['fill balance and gate timing','venting','material thermal condition','cavity/runner restriction'],avoid:'Assessing only appearance; location can alter structural performance.'},
    {name:'Part mass plateaus during hold study',pattern:'Increasing hold time no longer changes mass under stable conditions.',first:['confirm repeatability and cooling','correlate dimensions/pressure if relevant','document gate-seal evidence'],avoid:'Assuming more hold time always adds useful packing.'},
    {name:'Dryer display looks normal but splay persists',pattern:'Dryer temperature/dew-point display is normal, yet moisture symptoms remain.',first:['measure material moisture with approved method','check airflow and residence','look for leaks/bypass','inspect post-dryer exposure'],avoid:'Treating one dryer display value as proof of dry material.'},
    {name:'New material lot changes pressure',pattern:'Pressure/fill response changes at a documented material-lot change.',first:['confirm exact grade/lot','compare supplier COA where available','check moisture/conditioning','run controlled process comparison'],avoid:'Automatically editing the master recipe without evidence and approval.'},
    {name:'Rejects cluster after startup',pattern:'Quality is poor for early cycles then stabilises.',first:['mould and melt thermal stabilisation','purge/material transition','hot-runner balance','startup procedure compliance'],avoid:'Building permanent settings around a transient startup condition.'}
  ],
  glossary:[
    ['Back pressure','Resistance applied during screw recovery to influence plasticising and melt preparation.'],
    ['Cavity balance','Similarity of filling/packing response between cavities in a multi-cavity mould.'],
    ['Cavity pressure','Pressure measured within the mould cavity using a suitable sensor.'],
    ['Check ring / non-return valve','Screw-tip device intended to limit reverse melt flow during injection.'],
    ['Clamp force','Force keeping mould halves closed against cavity pressure.'],
    ['Cooling time','Defined cycle interval allocated to solidification before opening/ejection.'],
    ['Cushion','Screw position/material reserve remaining after the packing phase.'],
    ['Decompression','Controlled screw movement used on some processes to reduce nozzle pressure after recovery.'],
    ['DOE','Design of experiments: structured method for estimating factor effects and interactions.'],
    ['Draft','Taper that assists release of a moulded feature from the tool.'],
    ['Fill time','Elapsed time for the controlled cavity-filling phase.'],
    ['Fountain flow','Typical advancing flow pattern where material near the centre moves forward and turns toward the mould wall.'],
    ['Gate freeze / gate seal','Point at which useful pressure transmission through the gate has effectively stopped.'],
    ['Hold / pack','Pressure-controlled phase used after transfer to compensate shrinkage while pressure can still be transmitted.'],
    ['Hot runner','Heated runner system intended to keep polymer molten between machine nozzle and gate.'],
    ['MFR / MVR','Standardised melt-flow test results measured under specified conditions; not a complete moulding rheology curve.'],
    ['Mould shrinkage','Dimensional reduction from mould dimensions to the conditioned moulded part, dependent on material/process/geometry.'],
    ['Orientation','Directional arrangement of polymer chains or fibres created by flow and deformation.'],
    ['Parting line','Interface where mould halves or components separate.'],
    ['Plastic pressure','Pressure on the polymer side of the injection unit; machine conversion from hydraulic values is machine-specific.'],
    ['Residence time','Time material spends in the heated processing system; actual distribution is broader than one simple calculated value.'],
    ['Regrind','Previously processed material mechanically reduced for possible controlled reuse.'],
    ['Shear rate','Rate of deformation in flowing material; strongly influences apparent viscosity of polymer melts.'],
    ['Shear thinning','Decrease in apparent viscosity as shear rate increases, typical of many thermoplastic melts.'],
    ['Shot size','Metered volume/position prepared for injection; controller representation is machine-specific.'],
    ['Sink mark','Local surface depression associated with differential volumetric shrinkage and insufficient local compensation.'],
    ['Transfer','Change from velocity-controlled filling to pressure-controlled packing/holding.'],
    ['Venting','Designed escape path for displaced air/gas from the mould cavity.'],
    ['Viscosity','Resistance to flow; polymer melt viscosity depends on shear rate, temperature, pressure and material history.'],
    ['Warpage','Departure of a moulded part from intended shape due to non-uniform shrinkage, orientation, stress or thermal history.'],
    ['Weld / knit line','Region formed where two advancing flow fronts meet.'],
    ['Amorphous polymer','Polymer morphology without long-range crystalline order; moulding shrinkage and optical behaviour often differ from semi-crystalline materials.'],
    ['Semi-crystalline polymer','Polymer that forms ordered crystalline regions as it cools; cooling history can strongly affect shrinkage and properties.'],
    ['Anisotropy','Properties or dimensions that differ with direction, often due to flow orientation or fibre reinforcement.'],
    ['Cavity-to-cavity variation','Differences between cavities caused by local flow, cooling, tooling or sensor conditions.'],
    ['Intensification ratio','Machine-specific relationship used on some hydraulic machines to relate hydraulic and plastic pressure.'],
    ['Rational subgroup','SPC grouping chosen so within-group variation represents short-term/common conditions.'],
    ['Special cause','Variation signal associated with a specific change or event rather than routine common-cause variation.'],
    ['Common cause','Background variation inherent in the current process system.'],
    ['Thermal balance','Distribution and stability of heat removal/addition throughout mould and material system.'],
    ['Tool-safe / mould protection','Controlled low-force/low-pressure closing strategy intended to detect obstruction before full clamp force.'],
    ['Valve gate','Actuated hot-runner gate pin used to control gate opening/closing and flow timing.'],
    ['Cold slug','Relatively cool polymer portion that may enter the runner/cavity and create a visible or flow disturbance.'],
    ['Conditioning','Defined post-mould environmental exposure before measurement or use, important for some polymers such as polyamides.'],
    ['COA','Certificate of Analysis: supplier lot-level test/identity information where provided.'],
    ['Reaction plan','Predefined response when a process or quality control detects an out-of-control/out-of-specification condition.']
  ]
};

window.MM_REFERENCE_DATA=DATA;

function esc(v){return String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));}
function textOf(v){if(Array.isArray(v))return v.map(textOf).join(' ');if(v&&typeof v==='object')return Object.values(v).map(textOf).join(' ');return String(v??'');}
function searchable(item){return textOf(item).toLowerCase();}
function list(items){return `<ul>${(items||[]).map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`;}
function ensureUI(){
  if(!document.body||document.getElementById('mmrd-open'))return;
  const style=document.createElement('style');
  style.textContent=`
  #mmrd-open{position:fixed;left:14px;bottom:14px;z-index:2147483000;border:1px solid #41658d;background:#10233d;color:#eef7ff;border-radius:999px;padding:10px 14px;font:700 13px/1 system-ui,-apple-system,"Segoe UI",sans-serif;box-shadow:0 8px 24px rgba(0,0,0,.3);cursor:pointer}
  #mmrd-open:focus-visible,.mmrd button:focus-visible,.mmrd input:focus-visible{outline:3px solid #72e6cd;outline-offset:2px}
  .mmrd{position:fixed;inset:0;z-index:2147483001;background:rgba(2,8,18,.84);display:none;align-items:center;justify-content:center;padding:14px;font-family:system-ui,-apple-system,"Segoe UI",sans-serif;color:#eef7ff}
  .mmrd[data-open="1"]{display:flex}.mmrd-panel{width:min(1100px,100%);max-height:min(90vh,940px);overflow:hidden;background:#0e1a2c;border:1px solid #304866;border-radius:18px;box-shadow:0 24px 70px rgba(0,0,0,.55);display:flex;flex-direction:column}
  .mmrd-head{padding:18px 18px 12px;border-bottom:1px solid #253a54}.mmrd-title{display:flex;gap:10px;align-items:flex-start;justify-content:space-between}.mmrd-title h2{margin:0;font-size:22px}.mmrd-title p{margin:5px 0 0;color:#a9bdd6;font-size:13px;line-height:1.45}.mmrd-close{border:1px solid #49627e;background:#172941;color:#fff;border-radius:9px;padding:8px 11px;cursor:pointer}
  .mmrd-tools{display:grid;grid-template-columns:minmax(180px,1fr);gap:10px;margin-top:13px}.mmrd-search{width:100%;border:1px solid #3a5471;background:#081423;color:#fff;border-radius:10px;padding:10px 12px}.mmrd-tabs{display:flex;gap:6px;flex-wrap:wrap}.mmrd-tabs button{border:1px solid #3a5471;background:#13243a;color:#dceaff;border-radius:9px;padding:8px 10px;cursor:pointer}.mmrd-tabs button[aria-selected="true"]{background:#1f4d58;border-color:#55d6be;color:#fff}
  .mmrd-body{overflow:auto;padding:14px 18px 20px}.mmrd-count{font-size:12px;color:#9fb5cf;margin:0 0 10px}.mmrd-grid{display:grid;grid-template-columns:repeat(auto-fit,minmax(250px,1fr));gap:10px}.mmrd-card{border:1px solid #2b405b;background:#111f32;border-radius:12px;padding:13px}.mmrd-card h3{font-size:15px;margin:0 0 7px}.mmrd-card p{margin:5px 0;color:#c8d7e8;font-size:13px;line-height:1.45}.mmrd-card b{color:#fff}.mmrd-card ul{margin:5px 0 0;padding-left:18px;color:#c8d7e8;font-size:13px;line-height:1.45}.mmrd-note{margin:0 0 12px;padding:10px 12px;border-left:3px solid #55d6be;background:#10283a;color:#dcebf7;font-size:12px;line-height:1.5}.mmrd-empty{padding:24px;text-align:center;color:#9fb5cf}
  @media(max-width:650px){.mmrd{padding:0}.mmrd-panel{height:100%;max-height:none;border-radius:0;border:0}.mmrd-head{padding-top:max(14px,env(safe-area-inset-top))}.mmrd-body{padding-bottom:max(18px,env(safe-area-inset-bottom))}.mmrd-tabs{overflow-x:auto;flex-wrap:nowrap;padding-bottom:4px}.mmrd-tabs button{white-space:nowrap}}
  @media(prefers-reduced-motion:reduce){.mmrd *{scroll-behavior:auto!important}}
  `;
  document.head.appendChild(style);

  const open=document.createElement('button');
  open.id='mmrd-open';open.type='button';open.textContent='Reference Data';open.setAttribute('aria-haspopup','dialog');
  const modal=document.createElement('div');
  modal.className='mmrd';modal.setAttribute('role','dialog');modal.setAttribute('aria-modal','true');modal.setAttribute('aria-label','MouldMaster reference data');modal.dataset.open='0';
  modal.innerHTML=`<section class="mmrd-panel"><div class="mmrd-head"><div class="mmrd-title"><div><h2>Reference Data</h2><p>Search materials, defects, process signals, tooling, machines, quality, safety and troubleshooting.</p></div><button class="mmrd-close" type="button" aria-label="Close reference data">Close</button></div><div class="mmrd-tools"><input class="mmrd-search" type="search" placeholder="Search reference data…" aria-label="Search reference data"><div class="mmrd-tabs" role="tablist"></div></div></div><div class="mmrd-body"><p class="mmrd-note">${esc(DATA.note)}</p><p class="mmrd-count"></p><div class="mmrd-grid"></div></div></section>`;
  document.body.append(open,modal);

  const tabs=[['materials','Materials'],['defects','Defects'],['signals','Process signals'],['tooling','Tooling'],['machine','Machine'],['quality','Quality'],['safety','Safety'],['troubleshooting','Troubleshooting'],['glossary','Glossary']];
  let active='materials';
  const tabsBox=modal.querySelector('.mmrd-tabs'),search=modal.querySelector('.mmrd-search'),grid=modal.querySelector('.mmrd-grid'),count=modal.querySelector('.mmrd-count');
  for(const [key,label] of tabs){const b=document.createElement('button');b.type='button';b.textContent=label;b.dataset.key=key;b.setAttribute('role','tab');b.addEventListener('click',()=>{active=key;for(const x of tabsBox.children)x.setAttribute('aria-selected',String(x===b));render();});tabsBox.appendChild(b)}
  tabsBox.firstElementChild.setAttribute('aria-selected','true');

  function card(item){
    if(active==='materials')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p><b>Family:</b> ${esc(item.family)}</p><p><b>Traits:</b> ${esc(item.traits.join(', '))}</p><p><b>Watch:</b></p>${list(item.watch)}<p><b>Verify:</b> ${esc(item.verify)}</p></article>`;
    if(active==='defects')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p>${esc(item.evidence)}</p><p><b>Check:</b></p>${list(item.check)}<p><b>Avoid:</b> ${esc(item.avoid)}</p></article>`;
    if(active==='signals')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p><b>Meaning:</b> ${esc(item.meaning)}</p><p><b>Use:</b> ${esc(item.use)}</p><p><b>Drift:</b> ${esc(item.drift)}</p></article>`;
    if(active==='tooling')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p><b>Purpose:</b> ${esc(item.purpose)}</p><p><b>Inspect:</b></p>${list(item.inspect)}<p><b>Remember:</b> ${esc(item.remember)}</p></article>`;
    if(active==='machine')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p><b>Role:</b> ${esc(item.role)}</p><p><b>Watch:</b></p>${list(item.watch)}<p><b>Evidence:</b> ${esc(item.evidence)}</p></article>`;
    if(active==='quality')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p><b>Purpose:</b> ${esc(item.purpose)}</p><p><b>Good evidence:</b></p>${list(item.good)}<p><b>Risk:</b> ${esc(item.risk)}</p></article>`;
    if(active==='safety')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p><b>Check:</b> ${esc(item.check)}</p><p><b>Why:</b> ${esc(item.why)}</p><p><b>Never:</b> ${esc(item.never)}</p></article>`;
    if(active==='troubleshooting')return `<article class="mmrd-card"><h3>${esc(item.name)}</h3><p>${esc(item.pattern)}</p><p><b>Check first:</b></p>${list(item.first)}<p><b>Avoid:</b> ${esc(item.avoid)}</p></article>`;
    return `<article class="mmrd-card"><h3>${esc(item[0])}</h3><p>${esc(item[1])}</p></article>`;
  }
  function render(){
    const q=search.value.trim().toLowerCase();
    const all=DATA[active];
    const rows=all.filter(item=>!q||searchable(item).includes(q));
    count.textContent=`${rows.length} of ${all.length} ${tabs.find(x=>x[0]===active)[1].toLowerCase()}`;
    grid.innerHTML=rows.length?rows.map(card).join(''):'<div class="mmrd-empty">No matching reference data.</div>';
  }
  search.addEventListener('input',render);
  const close=()=>{modal.dataset.open='0';open.focus();};
  open.addEventListener('click',()=>{modal.dataset.open='1';render();setTimeout(()=>search.focus(),0)});
  modal.querySelector('.mmrd-close').addEventListener('click',close);
  modal.addEventListener('click',e=>{if(e.target===modal)close()});
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&modal.dataset.open==='1')close()});
  render();
}

if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',ensureUI,{once:true});else ensureUI();
})();