/* MouldMaster guided training upgrade v2 — content 2026.08.23.2 */
(function(){
'use strict';
const REVIEW_KEY='mm_spaced_review_v2', SIGN_KEY='mm_practical_signoff_v1', DAY=86400000;
const esc=v=>String(v??'').replace(/[&<>\"]/g,m=>({'&':'&amp;','<':'&lt;','>':'&gt;','\"':'&quot;'}[m]));
const load=(k,d)=>{try{const x=JSON.parse(localStorage.getItem(k)||'');return x&&typeof x==='object'?x:d}catch(_){return d}};
const save=(k,v)=>{try{localStorage.setItem(k,JSON.stringify(v))}catch(_){}};
const qt=q=>q?.q??q?.[0]??'', qo=q=>q?.options??q?.[1]??[], qc=q=>Number(q?.correct??q?.[2]??0), qw=q=>q?.explanation??q?.why??q?.[3]??'', qfb=q=>q?.optionFeedback??q?.feedback??q?.[6]??[], qu=q=>q?.sourceUrl??q?.url??q?.[5]??'', qr=q=>q?.reference??q?.source??q?.[4]??'';

const SRC={
 safety:[['ISO 20430:2020','Injection moulding machine safety requirements.','https://www.iso.org/standard/68000.html'],['HSE — Plastics processing safety','UK machinery and plastics-processing guidance.','https://www.hse.gov.uk/pubns/plasindx.htm'],['OSHA Injection Molding eTool','US machine guarding and safe-access guidance.','https://www.osha.gov/etools/machine-guarding/plastics-machinery/horizontal-injection-molding-machines'],['WorkSafe NZ — Safe use of machinery','NZ machinery risk-management guidance.','https://www.worksafe.govt.nz/topic-and-industry/machinery/safe-use-of-machinery/']],
 stats:[['NIST Engineering Statistics Handbook','Capability, measurement, DOE and statistical engineering.','https://www.itl.nist.gov/div898/handbook/'],['NIST — Process capability','Capability concepts and interpretation prerequisites.','https://www.itl.nist.gov/div898/handbook/pmc/section1/pmc16.htm'],['NIST — Experimental design','Factors, interactions, randomisation and blocking.','https://www.itl.nist.gov/div898/handbook/pri/section1/pri13.htm']],
 material:[['ISO 1133-1:2022','MFR/MVR testing under specified conditions.','https://www.iso.org/standard/83905.html'],['ASTM D1238','Melt-flow-rate test method for thermoplastics.','https://store.astm.org/standards/d1238'],['Trotta et al. (2021), Polymer Testing','Injection-moulding rheology and shear-thinning behaviour.','https://doi.org/10.1016/j.polymertesting.2021.107068'],['Hu et al. (2022), Polymers','Cooling-rate effects on polypropylene crystallisation.','https://doi.org/10.3390/polym14173646']],
 thermal:[['Autodesk Moldflow — Cooling stage','Cooling-stage heat removal and solidification background.','https://help.autodesk.com/cloudhelp/2023/ENU/MoldflowInsight-CLC-Ref-Materials/files/glossary-of-terminology/MoldflowInsight_CLC_Ref_Materials_glossary_of_terminology_Cooling_stage_html.html'],['Zhao et al. (2022), Int J Adv Manuf Technol','Review of injection-moulding warpage/shrinkage and interacting process parameters.','https://pubmed.ncbi.nlm.nih.gov/35194289/'],['Hu et al. (2022), Polymers','Cooling-rate effects on crystallisation behaviour.','https://doi.org/10.3390/polym14173646']],
 pack:[['Autodesk Moldflow — Packing guidance','Packing, hold and gate-freeze background.','https://help.autodesk.com/view/MOLDFLOW/2013/ENU/caas.html?url=caas%2Fvhelp%2Fhelp-dev-autodesk-com%2Fv%2FSimulation-Moldflow%2Fenu%2F2013%2FHelp%2F3Insight-360%2F3927-Process-3927%2F3933-Profiles3933%2F3945-Packing-3945.html'],['Zhao et al. (2022), Int J Adv Manuf Technol','Review of packing/cooling/process effects on shrinkage and warpage.','https://pubmed.ncbi.nlm.nih.gov/35194289/']],
 flow:[['Trotta et al. (2021), Polymer Testing','High-shear moulding rheology and shear thinning.','https://doi.org/10.1016/j.polymertesting.2021.107068'],['Zhao et al. (2022), Int J Adv Manuf Technol','Multi-parameter injection-moulding review.','https://pubmed.ncbi.nlm.nih.gov/35194289/']],
 tooling:[['ISO 20430:2020','Safety requirements at machine/tool interfaces.','https://www.iso.org/standard/68000.html'],['Zhao et al. (2022), Int J Adv Manuf Technol','Process/tooling interactions relevant to dimensional response.','https://pubmed.ncbi.nlm.nih.gov/35194289/']],
 automation:[['ISO 20430:2020','Injection moulding machinery safety requirements.','https://www.iso.org/standard/68000.html'],['OSHA Injection Molding eTool','Integrated guarding and safe access around moulding machinery.','https://www.osha.gov/etools/machine-guarding/plastics-machinery/horizontal-injection-molding-machines'],['WorkSafe NZ — Safe use of machinery','Machinery safeguarding and risk-control guidance.','https://www.worksafe.govt.nz/topic-and-industry/machinery/safe-use-of-machinery/']]
};
function categories(text){const t=String(text||'').toLowerCase(),c=[];if(/guard|safety|interlock|lockout|isolation|hazard|robot|cell/.test(t))c.push('safety');if(/capability|cpk|ppk|doe|statistics|measurement|random|factorial|validation|sampling/.test(t))c.push('stats');if(/material|polymer|rheology|viscosity|mfr|mvr|moisture|dry|crystall|degrad|residence|regrind/.test(t))c.push('material');if(/cool|temperature|thermal|warpage|shrink|ejection/.test(t))c.push('thermal');if(/pack|hold|gate seal|sink/.test(t))c.push('pack');if(/fill|flow|pressure loss|shear|jet|weld|short shot|vent|burn/.test(t))c.push('flow');if(/\bmould\b|\bmold\b|runner|gate|tool|cavity|draft|clamp/.test(t))c.push('tooling');if(/automation|sensor|vision|eoat|robot|mes|traceability/.test(t))c.push('automation');return [...new Set(c)];}
function refsFor(text,count=3){const out=[];for(const cat of categories(text))for(const s of (SRC[cat]||[]))if(!out.some(x=>x[2]===s[2]))out.push(s);return out.slice(0,count)}
function refsHTML(text,title='Evidence & further reading'){const a=refsFor(text);if(!a.length)return `<section class="mm-ref-panel"><span class="eyebrow">References</span><h3>${title}</h3><p>No general external source was auto-selected for this topic. Use the lesson rationale, current machine/tool documentation, approved site procedures and any source specifically cited by the question or material grade.</p></section>`;return `<section class="mm-ref-panel"><span class="eyebrow">References</span><h3>${title}</h3>${a.map(s=>`<a href="${s[2]}" target="_blank" rel="noopener"><b>${esc(s[0])}</b><small>${esc(s[1])}</small><em>Open ↗</em></a>`).join('')}<p>General references support mechanisms, not universal production settings. Current supplier data, machine documentation, approved procedures and applicable law control specific limits.</p></section>`}

const GUIDES=[
 [/cycle|phase/,['The moulding cycle is a sequence of filling, transfer, packing/holding, cooling, recovery and mould movement. Each phase has a different physical purpose.','Compare phase times and actual values with a known-good cycle.','A total cycle gets longer: first identify which phase changed.','Treating total cycle time as one number and missing the changing phase.']],
 [/setpoint|actual|controller/,['A setpoint is a command; an actual is evidence of what the machine and material actually did.','Trend fill time, peak pressure, transfer position, cushion and recovery time.','The recipe is unchanged but fill time drifts: compare actuals first.','Assuming equal recipes prove equal processes.']],
 [/cushion|non-return|check valve/,['Cushion and shot-delivery consistency help reveal how repeatably material was delivered and packed.','Trend cushion, transfer, pressure and part mass together.','Cushion and mass vary together: investigate delivery before compensating with hold.','Masking unstable delivery with more packing.']],
 [/moisture|dry|splay/,['Moisture-sensitive grades need grade-specific drying, handling and verification.','Check dryer performance, material history and the approved moisture method.','Splay follows humid exposure: verify moisture before unrelated machine changes.','Using one generic drying recipe for all resins.']],
 [/viscosity|rheology|shear|mfr|mvr/,['Thermoplastic apparent viscosity depends on shear rate, temperature and material history; most melts are shear-thinning.','Compare controlled fill-rate response and pressure while holding other conditions stable.','A speed study changes pressure response even when the material grade is unchanged.','Treating MFR as a complete moulding rheology curve.']],
 [/cool|warpage|shrink|temperature/,['Cooling and thermal balance affect solidification, shrinkage, ejection stability and warpage.','Track water condition, mould-surface temperature, ejection condition and dimensions.','A water-line change is followed by dimensional drift: verify the thermal system first.','Optimising cycle time without checking the quality boundary.']],
 [/pack|hold|gate seal|sink/,['Packing compensates volumetric shrinkage while the gate still transmits useful pressure.','Use part-mass/gate-seal evidence plus local geometry and cooling.','Part mass reaches a plateau: extra hold time may no longer transmit useful pressure.','Extending hold time after effective gate seal.']],
 [/short shot|burn|vent|weld|jet|flow/,['Flow defects are diagnosed by locating where the filling pattern, gas escape or joining flow fronts differ from the intended mechanism.','Use partial fills, pressure/fill-time actuals and physical flow-path evidence.','An end-fill burn points strongly toward gas escape/venting evidence.','Changing several unrelated settings at once.']],
 [/capability|cpk|ppk|measurement|doe|factor|random|validation/,['Statistical conclusions depend on stable processes, adequate measurement and a design that supports the question being asked.','Verify stability/measurement first; use DOE structure when interactions matter.','A factor run only late in the shift may be confounded with time.','Treating one capability number or unstructured trial as proof.']],
 [/guard|interlock|lockout|isolation|safety|robot|automation/,['Safeguards and authorised isolation are safety controls, not process variables.','Verify safeguard status and use the applicable site isolation/risk-control procedure.','A failed interlock is a safety defect, not a troubleshooting shortcut.','Bypassing protection to keep production running.']],
 [/runner|gate|cavity|draft|tooling|tool design|clamp|parting line|hot runner/,['Tooling geometry and condition shape flow, sealing, cooling and ejection; local defects often require local evidence.','Inspect the exact affected location and compare cavity/branch behaviour before global changes.','Local flash appears after tool work: inspect local seating/parting-line condition first.','Using a global process change to hide a local tooling fault.']]
];
const COURSE_GUIDES={
 'Foundations':['Injection moulding turns a controlled polymer melt into a repeatable part through filling, packing, cooling and ejection.','Identify the current cycle phase, relevant setpoints and measured actuals before drawing a conclusion.','Map a normal production cycle from material feed through part ejection.','Treating the whole process as one setting or one symptom.'],
 'Machine & Controls':['The machine creates and measures the motions, forces, temperatures and timing used by the process.','Compare commanded values, measured actuals and machine capability with a known-good cycle.','A recipe is unchanged but an actual drifts: investigate the machine response.','Assuming the controller display proves the physical process repeated.'],
 'Materials':['Material chemistry, grade, condition and processing history control how the polymer flows and performs.','Verify the exact grade, supplier data, handling history and relevant material condition.','Two grades share a family name but require different handling and validation.','Using family-level rules as a substitute for grade-specific evidence.'],
 'Mould Design':['Mould geometry, feeding, venting, cooling and ejection create local process conditions inside each cavity.','Compare cavities and inspect the affected flow path, vent, cooling circuit or ejection feature.','One cavity changes while the others remain stable: investigate local evidence first.','Using a global machine change to hide a local mould condition.'],
 'Process Setup':['A robust setup deliberately establishes filling, transfer, packing, cooling and recovery from a recorded baseline.','Record actuals and part responses while changing one authorised factor at a time.','Build a process window from controlled studies, then document its centre and limits.','Copying settings without confirming the transferred process.'],
 'Defect Troubleshooting':['A defect is evidence of one or more physical mechanisms, not a direct instruction to change a setting.','Locate the defect, compare known-good evidence and test the strongest competing causes.','A defect appears in one cavity: separate local from system-wide causes first.','Changing several variables at once until appearance improves.'],
 'Scientific Moulding':['Scientific moulding uses measured process studies to separate filling, transfer, packing, cooling and recovery effects.','Use repeatable actuals, controlled studies and confirmed responses rather than recipe values alone.','A viscosity or gate-seal study defines evidence for a process decision.','Calling an undocumented setting change a scientific study.'],
 'Capability & Validation':['Validation links a stable, measured process to defined product requirements and an approved control strategy.','Confirm measurement adequacy and stability before interpreting capability or validation evidence.','A capable result is supported by stable data, suitable measurement and a justified sampling plan.','Treating a single Cpk value as proof regardless of stability or measurement.'],
 'DOE & Statistics':['Designed experiments separate factor effects from noise only when their structure supports the conclusion.','Check randomisation, blocking, replication, interactions and measurement before accepting an effect.','A factor run only late in a shift may be confounded with time.','Changing many factors informally and calling the result a DOE.'],
 'Automation & Sensors':['Automation combines machinery, controls and people into one integrated system whose process and safety states must be designed together.','Verify sensor location, calibration, sequence logic, guarding and failure response.','A cavity sensor and machine sensor disagree because they measure different locations and events.','Assuming automation removes the need for integrated risk assessment.'],
 'Advanced Tooling & Simulation':['Advanced tooling and simulation predict local flow and thermal behaviour, but predictions must be checked against the real mould and process.','Compare model assumptions with cavity, cooling, pressure, temperature and part evidence.','A simulation trend is validated against short-shot or sensor evidence before release.','Treating a simulation image as proof without checking assumptions.'],
 'Expert Process Engineering':['Expert decisions integrate material, machine, mould, method, measurement, safety and economics without losing traceability.','State the competing mechanisms, evidence, constraints and confirmation test.','A change proposal includes technical evidence, risk, validation and control-plan impact.','Optimising one metric while ignoring system constraints and downstream risk.']
};
function packGuide(a){return {plain:a[0],evidence:a[1],example:a[2],mistake:a[3]}}
function guide(title,courseName){const t=String(title||'').toLowerCase();for(const [r,a] of GUIDES)if(r.test(t))return packGuide(a);return packGuide(COURSE_GUIDES[courseName]||COURSE_GUIDES['Expert Process Engineering'])}
function enrichLessons(D){D.lessons.forEach(l=>{l.mmGuide=guide(l.title,l.courseName)})}

const EXTRA=[
 ['Fill time drifts but recipe does not','Over an hour, fill time slowly increases while saved recipe values remain unchanged.',['Increase injection speed until the old fill time returns','Compare fill-time/pressure actuals, material condition and thermal actuals with the known-good baseline','Increase hold pressure','Change cooling time first'],1,'Setpoints do not prove the material or machine response stayed constant.'],
 ['One cavity becomes light','In an eight-cavity mould, one cavity gradually loses part mass while seven remain stable.',['Increase total shot size','Inspect the affected branch/gate and compare cavity balance before global changes','Increase hold time for every cavity','Reduce clamp force'],1,'A single-cavity change points first to local flow-path, gate, vent or thermal evidence.'],
 ['Recovery time becomes erratic','Recovery time becomes erratic and cushion variation appears at the same time.',['Check feed/material delivery, recovery actuals and shot-delivery consistency','Increase cooling time','Change clamp force','Change robot delay'],0,'Recovery and cushion evidence point toward feed/plasticising/shot delivery.'],
 ['Dimension shifts after water-line work','A critical dimension moves immediately after mould-water hoses were reconnected.',['Change hold pressure first','Verify circuit connection, flow and mould-surface temperature balance','Change transfer','Increase fill speed'],1,'The timing strongly implicates the changed thermal system.'],
 ['Part sticks after texture change','Ejection force rises after a new surface texture is added.',['Review draft, texture direction, local cooling/ejection and tooling condition','Raise packing','Increase fill speed','Let the robot pull harder'],0,'Texture changes release behaviour; review tooling/ejection evidence.'],
 ['Cpk drops after gauge change','Process and parts appear stable, but Cpk drops immediately after a new measurement fixture is introduced.',['Change moulding settings','Verify the measurement system before interpreting capability','Increase sample size only','Change specifications'],1,'A measurement-system change can alter observed variation.'],
 ['DOE result changes by run order','A factor appears important only when all high settings were run late in the shift.',['Accept the effect as proven','Consider time confounding and randomise/block appropriately','Remove replication','Change the specification'],1,'Run order can confound factor effects with time-related nuisance changes.'],
 ['Pressure sensor disagrees with machine','An in-cavity sensor trace changes while machine peak pressure is nearly constant.',['Assume one instrument is wrong','Recognise different measurement locations and investigate the local cavity event plus sensor health','Copy cavity pressure into the machine setpoint','Ignore the cavity sensor'],1,'Machine and local cavity pressure are different measurements.']
];
function addScenarios(D){const have=new Set((D.scenarios||[]).map(x=>x.title));for(const a of EXTRA)if(!have.has(a[0]))D.scenarios.push({title:a[0],situation:a[1],choices:a[2],correct:a[3],why:a[4],feedback:a[2].map((_,i)=>i===a[3]?a[4]:'This does not directly test the mechanism best supported by the evidence.')})}

const BANK_VERSION='2026.08.21.1';
function bankId(D,q,level,region){const text=qt(q);if(region){const a=D.regionalQuestions?.[region]?.[level]||[],i=a.findIndex(x=>qt(x)===text);return i>=0?`reg:${BANK_VERSION}:${region}:${level}:${i}`:null}const a=D.exams?.[level]||[],i=a.findIndex(x=>qt(x)===text);return i>=0?`tech:${BANK_VERSION}:${level}:${i}`:null}
function patchQuestionIds(D){const base=window.getExamQuestions;if(typeof base!=='function')return;window.getExamQuestions=function(level,region){const arr=base.apply(this,arguments);arr.forEach(q=>{q.mmId=bankId(D,q,level,q.region||null)||`legacy:${level}:${String(qt(q)).slice(0,80)}`});return arr}}
function findById(D,id){let m=/^tech:([^:]+):([^:]+):(\d+)$/.exec(id);if(m)return m[1]===BANK_VERSION?{level:m[2],q:D.exams?.[m[2]]?.[+m[3]]}:null;m=/^reg:([^:]+):([^:]+):([^:]+):(\d+)$/.exec(id);if(m)return m[1]===BANK_VERSION?{reg:m[2],level:m[3],q:D.regionalQuestions?.[m[2]]?.[m[3]]?.[+m[4]]}:null;m=/^tech:([^:]+):(\d+)$/.exec(id);if(m)return {level:m[1],q:D.exams?.[m[1]]?.[+m[2]]};m=/^reg:([^:]+):([^:]+):(\d+)$/.exec(id);if(m)return {reg:m[1],level:m[2],q:D.regionalQuestions?.[m[1]]?.[m[2]]?.[+m[3]]};return null}
function recordReview(q,ok,confidence){if(!q)return;const id=q.mmId||`legacy:${String(qt(q)).slice(0,160)}`,st=load(REVIEW_KEY,{items:{}}),x=st.items[id]||{id,stage:0,right:0,wrong:0,due:Date.now()};if(ok){x.right++;x.stage=Math.min(5,x.stage+1);if(confidence==='low')x.stage=Math.max(1,x.stage-1);x.due=Date.now()+([1,2,4,7,14,30][x.stage]||30)*DAY}else{x.wrong++;x.stage=0;x.due=Date.now()+DAY}x.last=Date.now();x.confidence=confidence||'medium';st.items[id]=x;save(REVIEW_KEY,st)}
function due(){return Object.values(load(REVIEW_KEY,{items:{}}).items||{}).filter(x=>x.due<=Date.now()||x.wrong>x.right).sort((a,b)=>(b.wrong-b.right)-(a.wrong-a.right)||a.due-b.due)}
function difficulty(level,i,q){if(q?.region)return level==='Advanced'?'Expert safety':'Applied safety';if(level==='Beginner')return i<3?'Foundation':'Applied';if(level==='Intermediate')return i<3?'Applied':'Diagnostic';return i<3?'Diagnostic':'Expert'}
function readHint(t){if(/checked first|check first/i.test(t))return 'Choose the first check that most directly tests the evidence.';if(/purpose/i.test(t))return 'Ask what job the phase, component or study is meant to do.';return 'Separate the symptom from the cause and choose the option best supported by measurable evidence.'}
function exactRefs(q){return qu(q)?[[qr(q)||'Question source','Source cited by this assessment item.',qu(q)]]:[]}

function lessonHTML(l){const g=l.mmGuide||guide(l.title,l.courseName);return `<section class="mm-teaching-grid" id="mmTeaching"><div class="mm-teach mm-plain"><span>PLAIN ENGLISH</span><h3>What this means</h3><p>${esc(g.plain)}</p></div><div class="mm-teach"><span>REAL MOULDING EXAMPLE</span><h3>What it looks like</h3><p>${esc(g.example)}</p></div><div class="mm-teach mm-mistake"><span>COMMON MISTAKE</span><h3>What to avoid</h3><p>${esc(g.mistake)}</p></div><div class="mm-teach"><span>EVIDENCE TO CHECK</span><h3>What would prove it?</h3><p>${esc(g.evidence)}</p></div></section>${refsHTML(l.title+' '+(l.courseName||''))}`}
function patchLesson(D){if(typeof window.renderLesson!=='function')return;const base=window.renderLesson;window.renderLesson=function(){base.apply(this,arguments);try{const l=typeof window.currentLesson==='function'?window.currentLesson():null,b=document.querySelector('#lesson .lesson-body');if(!l||!b)return;if(!b.querySelector('#mmTeaching'))(b.querySelector('.callout')||b.querySelector('h3')||b).insertAdjacentHTML('afterend',lessonHTML(l));const c=D.courses.find(x=>x.id===l.course);if(c&&!b.querySelector('.mm-lesson-progress')){const i=c.lessonIds.indexOf(l.id)+1;b.insertAdjacentHTML('afterbegin',`<div class="mm-lesson-progress"><div><b>Lesson ${i} of ${c.lessonIds.length}</b><span>${Math.round(i/c.lessonIds.length*100)}%</span></div><i><b style="width:${i/c.lessonIds.length*100}%"></b></i></div>`)}if(innerWidth<720&&!b.querySelector('.mm-mobile-lessons')){const side=document.querySelector('#lesson .lesson-side');if(side){const x=document.createElement('button');x.className='secondary mm-mobile-lessons';x.textContent='☰ Lesson list';x.onclick=()=>side.classList.toggle('mm-open');b.prepend(x)}}}catch(_){}}}
function patchExam(){
 if(typeof window.startExam!=='function'||typeof window.gradeExam!=='function')return;
 const start=window.startExam,grade=window.gradeExam;
 window.startExam=function(level){
  const r=start.apply(this,arguments);
  if(window.activeExam)window.activeExam.mmSubmitted=false;
  setTimeout(()=>document.querySelectorAll('#examQuestions .question').forEach((el,i)=>{
   const q=window.activeExam?.questions?.[i];if(!q||el.querySelector('.mm-qmeta'))return;
   el.querySelector('b')?.insertAdjacentHTML('afterend',`<div class="mm-qmeta"><span>${esc(difficulty(level,i,q))}</span><span>References after grading</span></div><div class="question-plain-language"><b>How to read this:</b> ${esc(readHint(qt(q)))}</div>`);
   el.insertAdjacentHTML('beforeend',`<div class="mm-confidence"><b>Confidence:</b><label><input type="radio" name="conf${i}" value="low"> Low</label><label><input type="radio" name="conf${i}" value="medium" checked> Medium</label><label><input type="radio" name="conf${i}" value="high"> High</label></div>`);
  }),0);
  return r;
 };
 window.gradeExam=function(level){
  const exam=window.activeExam;
  if(!exam)return grade.apply(this,arguments);
  if(exam.mmSubmitted){window.toast?.('This attempt has already been graded. Start a new exam to try again.');return false}
  exam.mmSubmitted=true;
  const qs=exam.questions||[],res=qs.map((q,i)=>{const a=document.querySelector(`input[name=ex${i}]:checked`),c=document.querySelector(`input[name=conf${i}]:checked`);return {q,sel:a?+a.value:null,conf:c?.value||'medium'}});
  let r;
  try{r=grade.apply(this,arguments)}catch(e){exam.mmSubmitted=false;throw e}
  document.querySelectorAll('#examQuestions input').forEach(x=>x.disabled=true);
  const gradeButton=[...document.querySelectorAll('#examQuestions ~ button, #modal button')].find(x=>/grade/i.test(x.textContent||''));
  if(gradeButton){gradeButton.disabled=true;gradeButton.textContent='Attempt graded'}
  res.forEach(x=>recordReview(x.q,x.sel===qc(x.q),x.conf));
  setTimeout(()=>{
   const host=document.querySelector('#answerReview');if(!host||document.querySelector('.mm-learning-debrief'))return;
   const html=res.map((x,i)=>{const o=qo(x.q),f=qfb(x.q),cr=qc(x.q),refs=exactRefs(x.q);return `<details class="mm-debrief"><summary>${x.sel===cr?'✓':'↻'} Question ${i+1} · ${esc(difficulty(level,i,x.q))} · ${esc(x.conf)} confidence</summary><div><h4>Why the best answer is best</h4><p>${esc(qw(x.q)||'The best answer follows the mechanism and evidence described in the question.')}</p><h4>Why the other choices are weaker</h4><ul>${o.map((v,j)=>j===cr?'':`<li><b>${esc(v)}</b> — ${esc(f[j]||'This choice does not test the strongest mechanism supported by the evidence.')}</li>`).join('')}</ul><h4>References</h4>${refs.length?refs.map(s=>`<a class="mm-ref-link" href="${s[2]}" target="_blank" rel="noopener"><b>${esc(s[0])}</b><small>${esc(s[1])}</small></a>`).join(''):'<p>No external source was attached to this item; use its audited rationale.</p>'}</div></details>`}).join('');
   host.insertAdjacentHTML('afterend',`<section class="mm-learning-debrief"><h3>Learning debrief</h3><p>This submitted attempt is locked. Wrong choices are explained as misconceptions, not recommended process changes.</p>${html}</section>`);
  },0);
  return r;
 };
}
window.mmOpenReview=function(){const D=window.MM_DATA,items=due().map(x=>({x,z:findById(D,x.id)})).filter(v=>v.z?.q).slice(0,10);if(!items.length){window.openModal?.('<h2>Review weak areas</h2><div class="callout">Nothing is due right now.</div>');return}window.mmReviewItems=items;window.openModal?.(`<span class="eyebrow">Spaced repetition</span><h2>Review weak areas</h2>${items.map((v,i)=>`<div class="question"><b>${i+1}. ${esc(qt(v.z.q))}</b>${qo(v.z.q).map((o,j)=>`<label class="option"><input type="radio" name="rv${i}" value="${j}"> ${esc(o)}</label>`).join('')}<button class="secondary" onclick="mmCheckReview(${i},this)">Check answer</button><div class="feedback hidden"></div></div>`).join('')}`)};
window.mmCheckReview=function(i,b){const v=window.mmReviewItems?.[i],q=v?.z?.q,r=document.querySelector(`input[name=rv${i}]:checked`),f=b.parentElement.querySelector('.feedback');if(!q||!r){f.classList.remove('hidden');f.textContent='Choose an answer first.';return}q.mmId=v.x.id;const ok=+r.value===qc(q);recordReview(q,ok,'medium');f.classList.remove('hidden');f.innerHTML=`<b>${ok?'Correct ✓':'Review again'}</b><br>${esc(qw(q))}`;b.disabled=true};
function patchExamHome(){if(typeof window.renderExams!=='function')return;const base=window.renderExams;window.renderExams=function(){base.apply(this,arguments);const h=document.querySelector('#exams');if(h&&!h.querySelector('.mm-review-card'))h.insertAdjacentHTML('afterbegin',`<div class="card mm-review-card"><div><span class="eyebrow">Spaced repetition</span><h3>Review weak areas</h3><p>Missed and low-confidence questions return on an increasing schedule using stable question-bank IDs.</p></div><div><b>${due().length}</b><span>due / weak</span><button class="secondary" onclick="mmOpenReview()">Start review</button></div></div>`)}}

const SIGN=['Identify guarded danger zones and explain why safeguards must remain effective','Explain the purpose of each major moulding-cycle phase','Distinguish setpoints from measured actuals','Recognise V/P transfer, cushion and shot-delivery evidence','Verify material identity and grade-specific handling information','Use safe authorised troubleshooting methods','Recognise common defect mechanisms','Collect a known-good baseline before process changes','Explain cavity-balance or partial-fill evidence','Explain gate-seal evidence','Interpret a simple process trend','Escalate conditions requiring maintenance, engineering or safety authority'];
const signData=()=>load(SIGN_KEY,{checks:{},supervisor:'',date:'',notes:''});
window.mmSaveSignoff=function(){const d=signData();SIGN.forEach((_,i)=>d.checks[i]=!!document.querySelector(`#mmSign${i}`)?.checked);d.supervisor=document.querySelector('#mmSupervisor')?.value||'';d.date=document.querySelector('#mmSignDate')?.value||'';d.notes=document.querySelector('#mmSignNotes')?.value||'';save(SIGN_KEY,d);window.toast?.('Practical sign-off saved locally')};
function signHTML(){const d=signData();return `<section class="card mm-signoff"><span class="eyebrow">Practical competency</span><h2>Supervisor sign-off</h2><p>This local workplace learning record is not an accredited licence or legal compliance certificate.</p><div class="mm-sign-progress"><b>${Object.values(d.checks).filter(Boolean).length}/${SIGN.length}</b> observed</div>${SIGN.map((x,i)=>`<label><input id="mmSign${i}" type="checkbox" ${d.checks[i]?'checked':''}> <span>${esc(x)}</span></label>`).join('')}<div class="mm-sign-grid"><label>Supervisor / assessor<input id="mmSupervisor" value="${esc(d.supervisor)}"></label><label>Date<input id="mmSignDate" type="date" value="${esc(d.date)}"></label></div><label>Evidence / notes<textarea id="mmSignNotes">${esc(d.notes)}</textarea></label><button class="primary" onclick="mmSaveSignoff()">Save practical record</button></section>`}
function patchCert(){if(typeof window.renderCertificates!=='function')return;const base=window.renderCertificates;window.renderCertificates=function(){base.apply(this,arguments);const h=document.querySelector('#certificates');if(h&&!h.querySelector('.mm-signoff'))h.insertAdjacentHTML('beforeend',signHTML())}}

function init(){const D=window.MM_DATA;if(!D||!Array.isArray(D.lessons)){setTimeout(init,100);return}if(window.__MM_TRAINING_V2__)return;window.__MM_TRAINING_V2__=true;enrichLessons(D);addScenarios(D);patchQuestionIds(D);patchLesson(D);patchExam();patchExamHome();patchCert();try{if(document.querySelector('#lesson:not(.hidden)'))window.renderLesson?.();if(document.querySelector('#exams:not(.hidden)'))window.renderExams?.()}catch(_){}}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',init);else init();
})();
