/* MouldMaster Book runtime — evidence-governed publication authorization. */
(function(){
  'use strict';
  const VERSION='2026.09.18.2';
  if(window.MMBook?.version===VERSION)return;
  const BOOK_DATA='./src/domains/learning/book-data/';
  const AUTH_PATH=`${BOOK_DATA}book-publication-authorization-v1.json`;
  const SME_PATH=`${BOOK_DATA}book-sme-review-v1.json`;
  const QUAL_PATH=`${BOOK_DATA}book-qualification-resolution-all-v1.json`;
  const HIGH_RISK_PATH=`${BOOK_DATA}book-claim-resolution-high-risk-v1.json`;
  const WORKED_CASES_PATH=`${BOOK_DATA}book-worked-engineering-cases-v1.json`;
  const BATCH_PATHS=[`${BOOK_DATA}book-authored-foundations-v1.json`,`${BOOK_DATA}book-evidence-registry-v1.json`,`${BOOK_DATA}book-chapters-materials-machine-v1.json`,`${BOOK_DATA}book-authored-remaining-v1.json`];
  const AUTH_GIT_BLOB_SHA1='af40aea0bc0dfb44598199089d7f3f78d0835189';
  const REQUIRED_INTEGRITY_FILES=['book-manifest-v1.json','book-sme-review-v1.json','book-qualification-resolution-all-v1.json','book-claim-resolution-high-risk-v1.json','book-authored-foundations-v1.json','book-evidence-registry-v1.json','book-chapters-materials-machine-v1.json','book-authored-remaining-v1.json','book-worked-engineering-cases-v1.json'];
  const CANONICAL_SOURCE_URLS=Object.freeze({
    'OUBELLAOUCH-2024-FIBRE-ORIENTATION':'https://doi.org/10.1007/s00170-024-12990-5',
    'BIELENBERG-2025-SWITCHOVER-REVIEW':'https://doi.org/10.3390/polym17081096',
    'ZHAO-2022-WARPAGE-SHRINKAGE-REVIEW':'https://doi.org/10.1007/s00170-022-08859-0',
    'PARIZS-2023-IN-MOLD-SENSORS':'https://doi.org/10.3390/s23031735',
    'LI-2024-WELD-LINE-REVIEW':'https://doi.org/10.1007/s00170-024-13607-7'
  });
  let manifest=null,publicationAuthorization=null,bookSmeReview=null,qualificationReview=null,highRiskReview=null,workedCaseLedger=null,workedCasesByChapter=new Map(),integrityMap=null,ui=null,previousView=null,open=false,contentsScrollY=0;
  const esc=value=>String(value??'').replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  const stateLabel=state=>({planned:'Planned','source-review':'Source review','technical-review':'Technical review',verified:'Evidence verified',hold:'Hold'}[state]||state);
  const fileName=path=>String(path||'').split('/').pop();
  const hex=buffer=>Array.from(new Uint8Array(buffer),b=>b.toString(16).padStart(2,'0')).join('');
  async function gitBlobSha1(bytes){
    if(!globalThis.crypto?.subtle)throw new Error('Book byte-integrity verification is unavailable in this browser');
    const body=new Uint8Array(bytes),header=new TextEncoder().encode(`blob ${body.byteLength}\0`),payload=new Uint8Array(header.byteLength+body.byteLength);
    payload.set(header,0);payload.set(body,header.byteLength);
    return hex(await crypto.subtle.digest('SHA-1',payload));
  }
  async function verifiedJson(path,expectedSha){
    const expected=expectedSha||integrityMap?.[fileName(path)];
    if(!/^[0-9a-f]{40}$/.test(String(expected||'')))throw new Error(`Book byte-integrity identity missing for ${fileName(path)}`);
    const r=await fetch(path,{cache:'no-store',credentials:'same-origin'});if(!r.ok)throw new Error(`${path} unavailable (${r.status})`);
    const bytes=await r.arrayBuffer(),actual=await gitBlobSha1(bytes);
    if(actual!==expected)throw new Error(`Book byte-integrity mismatch for ${fileName(path)}`);
    return JSON.parse(new TextDecoder('utf-8',{fatal:true}).decode(bytes));
  }
  function validateIntegrityAuthorization(auth){
    const cfg=auth?.runtimeIntegrity;
    if(cfg?.algorithm!=='git-blob-sha1'||!cfg.gitBlobSha1ByFile||typeof cfg.gitBlobSha1ByFile!=='object')throw new Error('Book publication authorization byte-integrity contract missing');
    for(const name of REQUIRED_INTEGRITY_FILES)if(!/^[0-9a-f]{40}$/.test(String(cfg.gitBlobSha1ByFile[name]||'')))throw new Error(`Book publication authorization integrity coverage missing: ${name}`);
    integrityMap=Object.freeze({...cfg.gitBlobSha1ByFile});
  }
  function applyPublicationAuthorization(data,declared,auth){
    if(auth?.schema!==1||auth?.bookId!==data.bookId)throw new Error('Book publication authorization identity check failed');if(auth.status!=='authorized')return;
    if(auth?.authorizationBasis?.sourceRevision!=='7ef28bd8b02994223e320fda64e99808357d3219')throw new Error('Book publication authorization source revision mismatch');
    if(auth?.governanceSnapshot?.manifestVersion!==data.version)throw new Error('Book publication authorization manifest version mismatch');const snapshot=auth.governanceSnapshot||{};
    if(snapshot.chapters!==46||snapshot.claims!==137||snapshot.supported!==116||snapshot.qualified!==21||snapshot.hold!==0||snapshot.conflicting!==0||snapshot.scopeQualifiedClaimsBlockingPublication!==0)throw new Error('Book publication authorization governance snapshot mismatch');
    const ids=Array.isArray(auth.authorizedChapterIds)?auth.authorizedChapterIds:[];if(ids.length!==declared.size||new Set(ids).size!==ids.length)throw new Error('Book publication authorization chapter coverage mismatch');
    for(const id of ids){const chapter=declared.get(id);if(!chapter)throw new Error(`Book publication authorization contains unknown chapter: ${id}`);chapter.state='verified';}publicationAuthorization=auth;
  }
  function validateSmeReview(data,declared){
    if(data?.schemaVersion!==1||data?.bookId!=='mouldmaster-book'||!Array.isArray(data.chapterIds)||!Array.isArray(data.reviews))throw new Error('Book SME review contract identity check failed');
    if(data.chapterIds.length!==declared.size||new Set(data.chapterIds).size!==data.chapterIds.length)throw new Error('Book SME review chapter coverage mismatch');for(const id of data.chapterIds)if(!declared.has(id))throw new Error(`Book SME review contains unknown chapter: ${id}`);if(workedCaseLedger){const expected=workedCaseLedger.cases.map(x=>x.id),actual=Array.isArray(data.workedCaseIds)?data.workedCaseIds:[];if(data.release!==VERSION||actual.length!==expected.length||expected.some(id=>!actual.includes(id)))throw new Error('Book SME worked-case scope mismatch');}
    const approved=new Set();for(const review of data.reviews){if(!review?.chapterId||!declared.has(review.chapterId))throw new Error(`Book SME review record has unknown chapter: ${review?.chapterId||'missing'}`);if(review.conclusion==='approved')approved.add(review.chapterId);}if(data.status==='validated'&&approved.size!==declared.size)throw new Error('Book SME review cannot be validated without approval coverage for every chapter');return data;
  }
  function validateQualificationReview(data){if(data?.schema!==1||data?.bookId!=='mouldmaster-book'||!Array.isArray(data.resolutions)||!Array.isArray(data.remainingQualifiedClaims))throw new Error('Book qualification-resolution identity check failed');const c=data.effectiveCountsAfterQualificationReview||{};if(c.chapters!==46||c.claims!==137||c.supported!==116||c.qualified!==21||c.hold!==0||c.conflicting!==0)throw new Error('Book qualification-resolution counts mismatch');return data;}
  function validateWorkedCases(data,declared,sourceMap,manifestData,auth){
    if(data?.schemaVersion!==1||data?.bookId!=='mouldmaster-book'||data?.release!==VERSION||data?.status!=='authorized-synthetic-teaching'||!Array.isArray(data.cases)||!Array.isArray(data.sourceSeeds))throw new Error('Book worked-case ledger identity check failed');
    const permit=auth?.workedCasesAuthorization;if(permit?.status!=='authorized'||permit?.release!==VERSION||permit?.ledger!=='data/book-worked-engineering-cases-v1.json'||permit?.caseCount!==10||permit?.claimCount!==10||permit?.independentSmeStatus!=='hold')throw new Error('Book worked-case publication authorization missing');
    for(const source of data.sourceSeeds){if(!source?.id||!source?.title||!source?.url||!source?.scope)throw new Error('Incomplete worked-case evidence source');if(sourceMap.has(source.id))throw new Error(`Duplicate worked-case source id: ${source.id}`);sourceMap.set(source.id,source);manifestData.sourceSeeds.push(source);}
    if(data.cases.length!==10)throw new Error('Book worked-case count mismatch');const caseIds=new Set(),chapterIds=new Set(),claimIds=new Set();
    for(const item of data.cases){
      if(!item?.id||caseIds.has(item.id))throw new Error(`Duplicate or missing worked-case id: ${item?.id||'missing'}`);caseIds.add(item.id);
      if(!item?.chapterId||chapterIds.has(item.chapterId)||!declared.has(item.chapterId))throw new Error(`Invalid worked-case chapter binding: ${item?.chapterId||'missing'}`);chapterIds.add(item.chapterId);
      if(item.synthetic!==true||!item.title||!item.setup||!item.interpretation||!Array.isArray(item.calculationSteps)||!item.calculationSteps.length||!Array.isArray(item.boundaries)||!item.boundaries.length)throw new Error(`Incomplete worked-case teaching contract: ${item.id}`);
      if(!Array.isArray(item.sourceIds)||!item.sourceIds.length)throw new Error(`Worked case lacks evidence anchors: ${item.id}`);for(const id of item.sourceIds)if(!sourceMap.has(id))throw new Error(`Unknown worked-case source ${id} in ${item.id}`);
      if(!Array.isArray(item.claims)||item.claims.length!==1)throw new Error(`Worked case must have one governed case claim: ${item.id}`);
      const claim=item.claims[0];if(!claim?.id||claimIds.has(claim.id)||claim.conclusion!=='supported-with-explicit-synthetic-scope'||!claim.statement)throw new Error(`Invalid worked-case claim: ${item.id}`);claimIds.add(claim.id);for(const id of claim.sourceIds||[])if(!sourceMap.has(id))throw new Error(`Unknown worked-case claim source ${id} in ${claim.id}`);
    }
    const authority=data.authorityBoundary||{};if(authority.productionUse!=='advisory-only'||authority.validatedRecipeAuthority!==false||authority.automaticMachineControl!==false||authority.universalSetpoints!==false)throw new Error('Worked-case authority boundary weakened');
    return data;
  }
  function smeStatusText(){if(!bookSmeReview)return 'Independent human SME review: status unavailable — do not infer approval.';const total=bookSmeReview.chapterIds.length,approved=new Set(bookSmeReview.reviews.filter(r=>r?.conclusion==='approved').map(r=>r.chapterId)).size;return `Independent human SME review: ${bookSmeReview.status==='validated'&&approved===total?'validated':'pending'} — ${approved}/${total} chapters approved.`;}
  function canonicalUrl(source){return publicationAuthorization?.canonicalAcademicEvidenceUrls?.[source?.id]||CANONICAL_SOURCE_URLS[source?.id]||source?.canonicalUrl||source?.url||'';}
  async function loadManifest(){
    const auth=await verifiedJson(AUTH_PATH,AUTH_GIT_BLOB_SHA1);validateIntegrityAuthorization(auth);
    const data=await verifiedJson(`${BOOK_DATA}book-manifest-v1.json`);if(data?.schema!==1||data?.bookId!=='mouldmaster-book'||!Array.isArray(data.parts)||!Array.isArray(data.sourceSeeds))throw new Error('Book manifest identity check failed');
    const declared=new Map((data.parts||[]).flatMap(p=>p.chapters||[]).map(ch=>[ch.id,ch]));if(declared.size!==(data.parts||[]).reduce((n,p)=>n+(p.chapters||[]).length,0))throw new Error('Duplicate chapter id in Book manifest');
    const sourceMap=new Map((data.sourceSeeds||[]).map(source=>[source.id,source]));if(sourceMap.size!==data.sourceSeeds.length)throw new Error('Duplicate source id in Book manifest');const authoredIds=new Set(),batches=await Promise.all(BATCH_PATHS.map(path=>verifiedJson(path)));
    for(const batch of batches){if(batch?.schema!==1||batch?.bookId!==data.bookId||!Array.isArray(batch.chapters))throw new Error('Book authored-batch identity check failed');for(const source of batch.sourceSeeds||[]){if(!source?.id||!source?.title||!source?.url||!source?.scope)throw new Error('Incomplete Book source record');if(sourceMap.has(source.id))throw new Error(`Duplicate authored source id: ${source.id}`);sourceMap.set(source.id,source);data.sourceSeeds.push(source);}for(const authored of batch.chapters){if(!authored?.id||authoredIds.has(authored.id))throw new Error(`Duplicate authored chapter id: ${authored?.id||'missing'}`);authoredIds.add(authored.id);const chapter=declared.get(authored.id);if(!chapter)throw new Error(`Authored chapter is not declared in manifest: ${authored.id}`);const effectiveState=authored.state||(batch.status==='technical-review'?'technical-review':chapter.state);if(effectiveState==='verified')throw new Error(`Authored draft cannot self-promote to verified: ${authored.id}`);if(!authored.applicability||!Array.isArray(authored.sections)||!authored.sections.length)throw new Error(`Incomplete authored chapter: ${authored.id}`);for(const sourceId of authored.sourceIds||[])if(!sourceMap.has(sourceId))throw new Error(`Unknown source ${sourceId} in ${authored.id}`);Object.assign(chapter,authored,{state:effectiveState});}}
    if(authoredIds.size!==declared.size)throw new Error('Book authored chapter coverage is incomplete');
    qualificationReview=validateQualificationReview(await verifiedJson(QUAL_PATH));
    highRiskReview=await verifiedJson(HIGH_RISK_PATH);if(highRiskReview?.schema!==1||highRiskReview?.bookId!==data.bookId)throw new Error('Book high-risk evidence identity mismatch');
    for(const ledger of [highRiskReview,qualificationReview])for(const source of ledger?.newEvidence||[])if(source?.id&&!sourceMap.has(source.id))sourceMap.set(source.id,source);
    workedCaseLedger=validateWorkedCases(await verifiedJson(WORKED_CASES_PATH),declared,sourceMap,data,auth);workedCasesByChapter=new Map(workedCaseLedger.cases.map(item=>[item.chapterId,item]));
    bookSmeReview=validateSmeReview(await verifiedJson(SME_PATH),declared);
    applyPublicationAuthorization(data,declared,auth);return data;
  }
  const allChapters=()=> (manifest?.parts||[]).flatMap(part=>part.chapters||[]),verifiedChapters=()=>allChapters().filter(ch=>ch.state==='verified');
  function evidenceMap(){const map=new Map((manifest?.sourceSeeds||[]).map(x=>[x.id,x]));for(const ledger of [highRiskReview,qualificationReview])for(const x of ledger?.newEvidence||[])if(x?.id&&!map.has(x.id))map.set(x.id,x);return map;}
  function evidenceItem(id){const s=evidenceMap().get(id);if(!s)return `<code>${esc(id)}</code>`;const label=esc(s.title||s.id),meta=esc([s.issuer,s.scope].filter(Boolean).join(' — ')),url=canonicalUrl(s);return url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer"><b>${label}</b></a>${meta?`<br><small>${meta}</small>`:''}`:`<b>${label}</b>${meta?`<br><small>${meta}</small>`:''}`;}
  function sourceHtml(chapter){const sources=(chapter.sourceIds||[]).map(id=>(manifest.sourceSeeds||[]).find(s=>s.id===id)).filter(Boolean);return sources.length?`<h4>Chapter evidence anchors</h4><ul>${sources.map(s=>{const url=canonicalUrl(s);return `<li>${url?`<a href="${esc(url)}" target="_blank" rel="noopener noreferrer"><b>${esc(s.title)}</b></a>`:`<b>${esc(s.title)}</b>`}<br><small>${esc(s.id)} — ${esc(s.scope)}</small></li>`}).join('')}</ul>`:'<p>No chapter source anchor has been attached.</p>';}
  function claimTraceHtml(chapter){if(!qualificationReview)return '<p><small>Publication claim trace unavailable.</small></p>';const prefix=`${chapter.id}-`,resolved=(qualificationReview.resolutions||[]).filter(x=>String(x.claimId||'').startsWith(prefix)),qualified=(qualificationReview.remainingQualifiedClaims||[]).filter(x=>String(x.claimId||'').startsWith(prefix));if(!resolved.length&&!qualified.length)return '<p><small>No later qualification decision changed this chapter; use the attached chapter anchors and governed publication authorization.</small></p>';const rows=resolved.map(x=>`<li><b>${esc(x.claimId)} — ${esc(x.newConclusion||'reviewed')}</b><p>${esc(x.reason||'')}</p>${(x.evidence||[]).length?`<ul>${x.evidence.map(id=>`<li>${evidenceItem(id)}</li>`).join('')}</ul>`:''}</li>`).join(''),qs=qualified.map(x=>`<li><b>${esc(x.claimId)} — scope-qualified</b><p>${esc(x.reason||'')}</p><small>${esc(x.qualificationType||'scope boundary')} · publication blocking: ${x.blockingPublication?'yes':'no'}</small></li>`).join('');return `<details class="mm-book-claim-trace"><summary><b>Publication claim trace</b> — why this wording was authorized</summary><p>This trace shows final evidence upgrades and deliberate scope qualifications. It supplements, rather than replaces, the chapter's source anchors.</p><ul>${rows}${qs}</ul></details>`;}
  function workedCaseHtml(chapter){const item=workedCasesByChapter.get(chapter.id);if(!item)return '';const list=(title,rows)=>Array.isArray(rows)&&rows.length?`<h4>${esc(title)}</h4><ul>${rows.map(x=>`<li>${esc(x)}</li>`).join('')}</ul>`:'';const table=item.table&&Array.isArray(item.table.columns)&&Array.isArray(item.table.rows)?`<div class="mm-book-table-wrap"><table><thead><tr>${item.table.columns.map(x=>`<th scope="col">${esc(x)}</th>`).join('')}</tr></thead><tbody>${item.table.rows.map(row=>`<tr>${row.map((x,i)=>i===0?`<th scope="row">${esc(x)}</th>`:`<td>${esc(x)}</td>`).join('')}</tr>`).join('')}</tbody></table></div>`:'';return `<section class="mm-book-worked-case" data-mm-worked-case="${esc(item.id)}"><span class="eyebrow">Worked example — synthetic teaching data</span><h3>${esc(item.title)}</h3><p>${esc(item.setup)}</p>${table}${list('Observations',item.observations)}${list('Assumptions',item.assumptions)}${list('Units',item.units)}${list('Calculation / reasoning',item.calculationSteps)}<h4>Interpretation</h4><p>${esc(item.interpretation)}</p>${list('Boundaries',item.boundaries)}<h4>Evidence anchors</h4><ul>${item.sourceIds.map(id=>`<li>${evidenceItem(id)}</li>`).join('')}</ul><p><small>Case claim: ${esc(item.claims[0].id)} · ${esc(item.claims[0].conclusion)}. Independent human SME review remains pending.</small></p></section>`;}
  function verifiedChapterHtml(chapter){const sections=Array.isArray(chapter.sections)?chapter.sections:[];return `<article class="mm-book-verified-chapter" data-mm-book-verified-chapter="${esc(chapter.id)}"><span class="eyebrow">Evidence verified</span><h2>${esc(chapter.title)}</h2><p><b>Applicability:</b> ${esc(chapter.applicability||'See attached evidence and controlling documentation.')}</p>${sections.map(s=>`<section><h3>${esc(s.title||'')}</h3><p>${esc(s.text||'')}</p></section>`).join('')}${workedCaseHtml(chapter)}${sourceHtml(chapter)}${claimTraceHtml(chapter)}</article>`;}
  function renderOverview(){if(!ui||!manifest)return;const verified=verifiedChapters(),review=allChapters().filter(ch=>ch.state==='technical-review');ui.summary.textContent=`${manifest.parts.length} parts · ${allChapters().length} governed chapters · ${review.length} in technical review · ${verified.length} evidence-verified for publication`;if(ui.smeStatus)ui.smeStatus.textContent=smeStatusText();ui.parts.innerHTML=(manifest.parts||[]).map((part,partIndex)=>`<section class="card"><span class="eyebrow">Part ${partIndex+1}</span><h3>${esc(part.title.replace(/^Part\s+\d+\s+[—-]\s*/,''))}</h3><div>${(part.chapters||[]).map((chapter,chapterIndex)=>`<button type="button" class="ghost mm-book-chapter-button" data-mm-book-chapter="${esc(chapter.id)}"><b>${chapterIndex+1}. ${esc(chapter.title)}</b><br><small>${esc(chapter.level)} · ${esc(stateLabel(chapter.state))}</small></button>`).join('')}</div></section>`).join('');ui.parts.querySelectorAll('[data-mm-book-chapter]').forEach(b=>b.addEventListener('click',()=>showChapter(b.dataset.mmBookChapter)));ui.listen.disabled=!verified.length;ui.listen.textContent=verified.length?'Listen to evidence-verified Book':'Listening unlocks after evidence verification';}
  function restoreBookChrome(){if(!ui)return;ui.hero.hidden=false;ui.accuracy.hidden=false;}function stopBookSpeech(){try{window.MMReadAloud?.stop?.();}catch(_){}}function bookScrollTop(){const main=document.querySelector('#mainContent,.main,main');return Math.max(0,window.scrollY||document.documentElement.scrollTop||main?.scrollTop||0);}function scrollBookReaderToTop(){requestAnimationFrame(()=>{if(!ui?.reader)return;ui.reader.scrollIntoView({block:'start',behavior:'auto'});const heading=ui.reader.querySelector('h2');if(heading){heading.setAttribute('tabindex','-1');heading.focus({preventScroll:true});}});}function showContents(){if(!ui)return;stopBookSpeech();restoreBookChrome();ui.reader.hidden=true;ui.contents.hidden=false;requestAnimationFrame(()=>window.scrollTo({top:contentsScrollY,behavior:'auto'}));}function bindBack(){ui?.reader?.querySelector('[data-mm-book-back]')?.addEventListener('click',showContents);}
  function showChapter(id){const chapter=allChapters().find(ch=>ch.id===id);if(!chapter||!ui)return;contentsScrollY=bookScrollTop();const sections=Array.isArray(chapter.sections)?chapter.sections:[];restoreBookChrome();const back='<button type="button" class="ghost" data-mm-book-back>← Book contents</button>';if(chapter.state==='verified')ui.reader.innerHTML=`${back}${verifiedChapterHtml(chapter)}`;else if(chapter.state==='technical-review'&&sections.length)ui.reader.innerHTML=`${back}<span class="eyebrow">Technical review draft — not evidence verified</span><h2>${esc(chapter.title)}</h2><p><b>Applicability:</b> ${esc(chapter.applicability||'Under review.')}</p><div class="callout"><b>Review boundary:</b> ${esc(chapter.reviewBoundary||'This draft is visible for technical review. Do not treat it as a machine setting, safety procedure or evidence-verified production instruction.')}</div>${sections.map(s=>`<section><h3>${esc(s.title||'')}</h3><p>${esc(s.text||'')}</p></section>`).join('')}${sourceHtml(chapter)}`;else ui.reader.innerHTML=`${back}<span class="eyebrow">${esc(stateLabel(chapter.state))}</span><h2>${esc(chapter.title)}</h2><p><b>This chapter is not being published as technical teaching content yet.</b></p><p>MouldMaster is reviewing the claims, applicability and sources first.</p>${sourceHtml(chapter)}`;ui.contents.hidden=true;ui.reader.hidden=false;bindBack();scrollBookReaderToTop();}
  function startVerifiedListening(){if(!ui)return;const verified=verifiedChapters();if(!verified.length)return;const reader=window.MMReadAloud,details=document.querySelector('.mm-read-aloud details'),play=document.querySelector('.mm-read-aloud [data-mm-read="play"]');if(!reader?.supported||!details||!play){ui.summary.textContent='Evidence-verified Book text is available to read, but device speech synthesis is unavailable.';return;}reader.stop?.();const back='<button type="button" class="ghost" data-mm-book-back>← Book contents</button>';ui.reader.innerHTML=`${back}${verified.map(verifiedChapterHtml).join('')}`;ui.contents.hidden=true;ui.hero.hidden=true;ui.accuracy.hidden=true;ui.reader.hidden=false;bindBack();scrollBookReaderToTop();requestAnimationFrame(()=>{reader.refresh?.();details.open=true;play.click();});}
  function openBook(){if(!ui)return;previousView=[...document.querySelectorAll('.view')].find(v=>!v.classList.contains('hidden')&&v!==ui.view)||previousView;document.querySelectorAll('.view').forEach(v=>v.classList.add('hidden'));ui.view.classList.remove('hidden');restoreBookChrome();open=true;document.querySelectorAll('#nav button').forEach(b=>b.classList.remove('active'));ui.nav.classList.add('active');const title=document.getElementById('pageTitle'),subtitle=document.getElementById('pageSubtitle');if(title)title.textContent='Book';if(subtitle)subtitle.textContent='Evidence-governed injection moulding reference — evidence-verified chapters retain explicit scope and source boundaries.';contentsScrollY=0;showContents();}
  function openChapter(id){openBook();showChapter(id);}
  function leaveBook(){if(!open)return;stopBookSpeech();open=false;ui?.view?.classList.add('hidden');ui?.nav?.classList.remove('active');}
  function searchBook(query){const q=String(query||'').trim().toLowerCase();if(q.length<2)return[];return allChapters().filter(ch=>[ch.title,ch.applicability,...(ch.sections||[]).flatMap(s=>[s.title,s.text])].join(' ').toLowerCase().includes(q)).slice(0,6);}
  function appendBookSearchResults(){const input=document.getElementById('globalSearch'),host=document.getElementById('searchResults');if(!input||!host||!manifest)return;const rows=searchBook(input.value);host.querySelectorAll('[data-mm-book-search-result]').forEach(x=>x.remove());for(const chapter of rows){const button=document.createElement('button');button.type='button';button.className='search-item';button.dataset.mmBookSearchResult='1';const title=document.createElement('b');title.textContent=`Book: ${chapter.title}`;const br=document.createElement('br'),meta=document.createElement('span');meta.className='muted tiny';meta.textContent=`${chapter.level} · evidence-governed chapter`;button.append(title,br,meta);button.addEventListener('click',()=>{try{window.closeModal?.()}catch(_){}openChapter(chapter.id)});host.appendChild(button);}}
  function installBookSearch(){if(window.__MM_BOOK_SEARCH_BOUND__)return;const base=window.doSearch;if(typeof base!=='function')return;window.doSearch=function(){const result=base.apply(this,arguments);appendBookSearchResults();return result};window.__MM_BOOK_SEARCH_BOUND__=VERSION;}
  function createUI(){const nav=document.getElementById('nav'),main=document.querySelector('#mainContent,.main,main');if(!nav||!main||document.getElementById('mmBookView'))return;const button=document.createElement('button');button.type='button';button.dataset.mmBookTab='1';button.innerHTML='<span class="mm-book-nav-icon" aria-hidden="true"></span><span>Book</span>';button.setAttribute('aria-label','Book');const listening=nav.querySelector('[data-mm-listening-tab]'),path=nav.querySelector('[data-view="path"]');(listening||path)?.insertAdjacentElement('afterend',button);if(!listening&&!path)nav.prepend(button);const view=document.createElement('section');view.id='mmBookView';view.className='view hidden';view.innerHTML=`<section class="card" data-mm-book-hero><span class="eyebrow">MouldMaster Book</span><h2>Injection moulding from foundations to advanced troubleshooting</h2><p>The Book is source-first and evidence-governed. Evidence-verified chapters retain their applicability and exclusions; machine, material, mould, hot-runner and workplace-specific requirements remain controlling.</p><p data-mm-book-summary>Loading governed Book manifest…</p><p data-mm-book-sme-status class="muted">Loading independent human SME review status…</p><div class="mm-book-hero-actions"><button type="button" class="ghost" data-mm-book-mode="listen" disabled>Listening unlocks after evidence verification</button></div></section><section data-mm-book-contents><div data-mm-book-parts></div></section><section class="card" data-mm-book-reader hidden></section><section class="card" data-mm-book-accuracy><h3>Accuracy and assurance boundary</h3><p><b>Evidence verified</b> means the generic Book wording passed MouldMaster's evidence and publication gates. It does not replace current grade, machine, mould, hot-runner, product or site-specific documentation.</p><p><b>Independent validation:</b> evidence verification does not imply independent human SME approval, physical-device validation, curriculum SME approval or learner-outcome validation. Those remain separate external gates.</p></section>`;main.appendChild(view);ui={view,nav:button,hero:view.querySelector('[data-mm-book-hero]'),accuracy:view.querySelector('[data-mm-book-accuracy]'),summary:view.querySelector('[data-mm-book-summary]'),smeStatus:view.querySelector('[data-mm-book-sme-status]'),parts:view.querySelector('[data-mm-book-parts]'),contents:view.querySelector('[data-mm-book-contents]'),reader:view.querySelector('[data-mm-book-reader]'),listen:view.querySelector('[data-mm-book-mode="listen"]')};button.addEventListener('click',e=>{e.preventDefault();e.stopPropagation();openBook();});ui.listen.addEventListener('click',startVerifiedListening);}
  async function init(){createUI();try{manifest=await loadManifest();renderOverview();installBookSearch();return manifest;}catch(error){if(ui){ui.summary.textContent='Book manifest, governed content or publication authorization could not be verified. Technical content remains unavailable.';if(ui.smeStatus)ui.smeStatus.textContent='Independent human SME review: status unavailable — do not infer approval.';ui.parts.innerHTML='<section class="card"><h3>Book unavailable</h3><p>The governed Book release failed its runtime identity or exact-byte checks, so MouldMaster has failed closed.</p></section>';}console.error('MouldMaster Book:',error);throw error;}}
  document.addEventListener('click',event=>{const target=event.target?.closest?.('nav button,[data-view],[data-page]');if(!target||target.dataset.mmBookTab)return;if(open)leaveBook();},true);
  let ready;
  window.MMBook=Object.freeze({version:VERSION,open:openBook,openChapter,search:searchBook,getManifest:()=>manifest,getPublicationAuthorization:()=>publicationAuthorization,getSmeReview:()=>bookSmeReview,getQualificationReview:()=>qualificationReview,getWorkedCases:()=>workedCaseLedger,getIntegrityMap:()=>integrityMap?{...integrityMap}:null,verifiedChapters,startVerifiedListening,get ready(){return ready;}});
  ready=document.readyState==='loading'?new Promise(resolve=>document.addEventListener('DOMContentLoaded',()=>resolve(init()),{once:true})).then(x=>x):init();
})();
