#!/usr/bin/env python3
from __future__ import annotations

import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
OUTPUT = ROOT / "BOOK_GOVERNANCE_STATUS.md"

def load(path: str):
    return json.loads((ROOT / path).read_text(encoding="utf-8"))

def need(ok, message: str):
    if not ok:
        raise AssertionError(message)

def render() -> str:
    version = load("version.json")
    manifest = load("data/book-manifest-v1.json")
    auth = load("data/book-publication-authorization-v1.json")
    gate = load("data/book-accuracy-gate-v1.json")
    audit = load("data/book-verification-audit-all-v1.json")
    reader = load("data/book-reader-architecture-v2.json")
    crosswalk = load("data/book-curriculum-crosswalk-v1.json")
    sme = load("data/book-sme-review-v1.json")
    binding = load("data/book-sme-release-binding-v1.json")
    external = load("data/release-external-validation-v1.json")

    modules = [ch for part in manifest["parts"] for ch in part["chapters"]]
    module_ids = [ch["id"] for ch in modules]
    reader_ids = [mid for chapter in reader["readerChapters"] for mid in chapter["moduleIds"]]
    auth_ids = list(auth["authorizedChapterIds"])
    cross_ids = [row["chapterId"] for row in crosswalk["chapterMappings"]]

    need(len(module_ids) == len(set(module_ids)), "Book manifest contains duplicate module IDs")
    need(sorted(reader_ids) == sorted(module_ids) and len(reader_ids) == len(module_ids),
         "reader architecture must cover every governed module exactly once")
    need(sorted(auth_ids) == sorted(module_ids), "publication authorization must cover every governed module")
    need(sorted(cross_ids) == sorted(module_ids) and len(cross_ids) == len(module_ids),
         "curriculum crosswalk must cover every governed module exactly once")
    need(auth.get("status") == "authorized", "current Book publication authorization is not authorized")
    need(auth.get("learnerFacingPublicationLabel") == "Source evidence reviewed",
         "learner-facing Book assurance label drifted")

    lifecycle = gate.get("recordLifecycle") or {}
    need(lifecycle.get("status") == "historical-prepublication-gate",
         "accuracy gate must be explicitly historical")
    need(
        lifecycle.get("supersededForCurrentPublicationStatusBy")
        == "data/book-publication-authorization-v1.json",
        "accuracy gate does not name the current publication authority",
    )

    need(sme.get("status") == "hold",
         "independent Book SME status must remain HOLD until genuine human evidence exists")
    need(binding.get("status") == "hold", "Book SME release binding must remain HOLD")
    need(binding.get("boundWebRelease") == version.get("web_release"),
         "Book SME binding must follow the current learner web release")
    need((external.get("bookSme") or {}).get("status") == "hold",
         "release ledger must keep Book SME external validation on HOLD")

    disposition = audit.get("effectiveClaimDisposition") or {}
    decision = audit.get("publicationDecision") or {}
    direct_sources = sum(1 for chapter in modules if chapter.get("sourceIds"))
    need(decision.get("chaptersReadyForExplicitPromotionReview") == len(module_ids),
         "verification audit chapter readiness count drifted")

    rows = [
        ("Learner web release", f"**{version['web_release']}**"),
        ("Book governed content release", f"**{auth['version']}**"),
        ("Publication authorization", f"**{auth['status']}**"),
        ("Learner-facing assurance label", f"**{auth['learnerFacingPublicationLabel']}**"),
        ("Independent human Book SME", f"**{sme['status'].upper()}**"),
        ("Governed modules", f"**{len(module_ids)}**"),
        ("Reader chapters", f"**{len(reader['readerChapters'])}**"),
        ("Curriculum-crosswalk coverage", f"**{len(cross_ids)}/{len(module_ids)}**"),
        ("Supported substantive claims", f"**{disposition.get('supported', 0)}**"),
        ("Scope-qualified claims", f"**{disposition.get('qualified', 0)}**"),
        ("Claim HOLD / conflicting",
         f"**{disposition.get('hold', 0)} / {disposition.get('conflicting', 0)}**"),
    ]

    lines = [
        "# MouldMaster Book governance status",
        "",
        "This file is generated by `tools/render_book_governance_status.py`. "
        "It is the human-readable current-state view; do not infer current publication "
        "status from an older ledger in isolation.",
        "",
        "## Current state",
        "",
        "| Boundary | Current value |",
        "| --- | --- |",
    ]
    lines.extend(f"| {name} | {value} |" for name, value in rows)
    lines += [
        "",
        "## How to read the historical records",
        "",
        f"- `data/book-manifest-v1.json` is the canonical **{len(module_ids)}-module inventory and source-seed record**. "
        "Its chapter workflow labels remain `source-review`; those labels are not the current publication-authority decision.",
        f"- `data/book-accuracy-gate-v1.json` is explicitly a **historical pre-publication gate**. "
        f"It records `{gate.get('currentBookDisposition')}` and `{gate.get('verifiedChapterCountAuthorizedByThisGate', 0)}` "
        "independently verified chapters at that earlier gate.",
        f"- `data/book-publication-authorization-v1.json` is the current publication authority. "
        f"It authorizes **{len(auth_ids)}/{len(module_ids)}** governed modules under the learner-facing label "
        f"**{auth['learnerFacingPublicationLabel']}**.",
        f"- The final claim-evidence stack resolves **{disposition.get('supported', 0)} supported + "
        f"{disposition.get('qualified', 0)} deliberately scope-qualified** claims, with "
        f"**{disposition.get('hold', 0)} HOLD and {disposition.get('conflicting', 0)} conflicting** effective claims.",
        f"- Only **{direct_sources}/{len(module_ids)}** manifest module rows carry direct seed `sourceIds`; "
        "final learner-facing evidence coverage is governed by the claim/evidence ledgers and publication authorization, "
        "not by that seed field alone.",
        f"- The reader architecture covers all **{len(module_ids)} modules exactly once** across "
        f"**{len(reader['readerChapters'])} reader chapters**. Reader grouping cannot add claims or upgrade evidence/SME status.",
        "",
        "## External evidence boundary",
        "",
        f"Independent Book SME review remains **{sme['status'].upper()}** and is bound to learner web release "
        f"**{binding['boundWebRelease']}**. Publication authorization does not create human SME approval, "
        "accreditation, physical-device validation, real assistive-technology validation, learner competence or production authority.",
        "",
        "Current release-external statuses:",
        "",
        f"- Real assistive technology: **{external['accessibility']['status'].upper()}**",
        f"- Physical PWA/device validation: **{external['pwaPhysicalDevices']['status'].upper()}**",
        f"- Windows external distribution validation: **{external['windowsDistribution']['status'].upper()}**",
        f"- Book SME: **{external['bookSme']['status'].upper()}**",
        f"- Curriculum SME: **{external['curriculumSme']['status'].upper()}**",
        f"- Learner outcomes: **{external['learnerOutcomes']['status'].upper()}**",
        f"- NZQA/provider: **{external['nzqaProvider']['status'].upper()}**",
        "",
        "## Current publication interpretation",
        "",
        f"The Book is authorized as a **{auth['publicationScope']}** with learner-facing assurance "
        f"**{auth['learnerFacingPublicationLabel']}**. It is not independently human-SME approved. "
        "The earlier technical-review-only gate remains preserved for audit history and must not be presented "
        "as the current publication decision.",
        "",
    ]
    return "\n".join(lines)

def main() -> None:
    parser = argparse.ArgumentParser()
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render()
    if args.check:
        actual = OUTPUT.read_text(encoding="utf-8") if OUTPUT.exists() else ""
        if actual != expected:
            raise SystemExit(
                "BOOK_GOVERNANCE_STATUS.md is stale; run python tools/render_book_governance_status.py"
            )
        print("Book governance status is current")
        return
    OUTPUT.write_text(expected, encoding="utf-8")
    print(f"Wrote {OUTPUT.relative_to(ROOT)}")

if __name__ == "__main__":
    main()
